// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IsOk struct {
	IsOk                 bool     `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsOk) Reset()         { *m = IsOk{} }
func (m *IsOk) String() string { return proto.CompactTextString(m) }
func (*IsOk) ProtoMessage()    {}
func (*IsOk) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *IsOk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsOk.Unmarshal(m, b)
}
func (m *IsOk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsOk.Marshal(b, m, deterministic)
}
func (m *IsOk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsOk.Merge(m, src)
}
func (m *IsOk) XXX_Size() int {
	return xxx_messageInfo_IsOk.Size(m)
}
func (m *IsOk) XXX_DiscardUnknown() {
	xxx_messageInfo_IsOk.DiscardUnknown(m)
}

var xxx_messageInfo_IsOk proto.InternalMessageInfo

func (m *IsOk) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

type BlockNumber struct {
	BlockNumber          int64    `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockNumber) Reset()         { *m = BlockNumber{} }
func (m *BlockNumber) String() string { return proto.CompactTextString(m) }
func (*BlockNumber) ProtoMessage()    {}
func (*BlockNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *BlockNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockNumber.Unmarshal(m, b)
}
func (m *BlockNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockNumber.Marshal(b, m, deterministic)
}
func (m *BlockNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockNumber.Merge(m, src)
}
func (m *BlockNumber) XXX_Size() int {
	return xxx_messageInfo_BlockNumber.Size(m)
}
func (m *BlockNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockNumber.DiscardUnknown(m)
}

var xxx_messageInfo_BlockNumber proto.InternalMessageInfo

func (m *BlockNumber) GetBlockNumber() int64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

type Address struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Addresses struct {
	Addresses            []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Addresses) Reset()         { *m = Addresses{} }
func (m *Addresses) String() string { return proto.CompactTextString(m) }
func (*Addresses) ProtoMessage()    {}
func (*Addresses) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *Addresses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Addresses.Unmarshal(m, b)
}
func (m *Addresses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Addresses.Marshal(b, m, deterministic)
}
func (m *Addresses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Addresses.Merge(m, src)
}
func (m *Addresses) XXX_Size() int {
	return xxx_messageInfo_Addresses.Size(m)
}
func (m *Addresses) XXX_DiscardUnknown() {
	xxx_messageInfo_Addresses.DiscardUnknown(m)
}

var xxx_messageInfo_Addresses proto.InternalMessageInfo

func (m *Addresses) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type BlockHash struct {
	BlockHash            string   `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHash) Reset()         { *m = BlockHash{} }
func (m *BlockHash) String() string { return proto.CompactTextString(m) }
func (*BlockHash) ProtoMessage()    {}
func (*BlockHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *BlockHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHash.Unmarshal(m, b)
}
func (m *BlockHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHash.Marshal(b, m, deterministic)
}
func (m *BlockHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHash.Merge(m, src)
}
func (m *BlockHash) XXX_Size() int {
	return xxx_messageInfo_BlockHash.Size(m)
}
func (m *BlockHash) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHash.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHash proto.InternalMessageInfo

func (m *BlockHash) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

type Balance struct {
	Balance              string   `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Balance) Reset()         { *m = Balance{} }
func (m *Balance) String() string { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()    {}
func (*Balance) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{5}
}

func (m *Balance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Balance.Unmarshal(m, b)
}
func (m *Balance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Balance.Marshal(b, m, deterministic)
}
func (m *Balance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Balance.Merge(m, src)
}
func (m *Balance) XXX_Size() int {
	return xxx_messageInfo_Balance.Size(m)
}
func (m *Balance) XXX_DiscardUnknown() {
	xxx_messageInfo_Balance.DiscardUnknown(m)
}

var xxx_messageInfo_Balance proto.InternalMessageInfo

func (m *Balance) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

type GasPrice struct {
	GasPrice             []byte   `protobuf:"bytes,1,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GasPrice) Reset()         { *m = GasPrice{} }
func (m *GasPrice) String() string { return proto.CompactTextString(m) }
func (*GasPrice) ProtoMessage()    {}
func (*GasPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{6}
}

func (m *GasPrice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GasPrice.Unmarshal(m, b)
}
func (m *GasPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GasPrice.Marshal(b, m, deterministic)
}
func (m *GasPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GasPrice.Merge(m, src)
}
func (m *GasPrice) XXX_Size() int {
	return xxx_messageInfo_GasPrice.Size(m)
}
func (m *GasPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_GasPrice.DiscardUnknown(m)
}

var xxx_messageInfo_GasPrice proto.InternalMessageInfo

func (m *GasPrice) GetGasPrice() []byte {
	if m != nil {
		return m.GasPrice
	}
	return nil
}

type IsFull struct {
	IsFull               bool     `protobuf:"varint,1,opt,name=is_full,json=isFull,proto3" json:"is_full,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsFull) Reset()         { *m = IsFull{} }
func (m *IsFull) String() string { return proto.CompactTextString(m) }
func (*IsFull) ProtoMessage()    {}
func (*IsFull) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{7}
}

func (m *IsFull) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsFull.Unmarshal(m, b)
}
func (m *IsFull) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsFull.Marshal(b, m, deterministic)
}
func (m *IsFull) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsFull.Merge(m, src)
}
func (m *IsFull) XXX_Size() int {
	return xxx_messageInfo_IsFull.Size(m)
}
func (m *IsFull) XXX_DiscardUnknown() {
	xxx_messageInfo_IsFull.DiscardUnknown(m)
}

var xxx_messageInfo_IsFull proto.InternalMessageInfo

func (m *IsFull) GetIsFull() bool {
	if m != nil {
		return m.IsFull
	}
	return false
}

type Block struct {
	Number               uint64         `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Hash                 string         `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	ParentHash           string         `protobuf:"bytes,3,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	Nonce                uint64         `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	MixHash              string         `protobuf:"bytes,5,opt,name=mix_hash,json=mixHash,proto3" json:"mix_hash,omitempty"`
	LogsBloom            []byte         `protobuf:"bytes,6,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	StateRoot            string         `protobuf:"bytes,7,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	Miner                string         `protobuf:"bytes,8,opt,name=miner,proto3" json:"miner,omitempty"`
	Difficulty           uint64         `protobuf:"varint,9,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	ExtraData            []byte         `protobuf:"bytes,10,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	Size                 uint64         `protobuf:"varint,11,opt,name=size,proto3" json:"size,omitempty"`
	GasLimit             uint64         `protobuf:"varint,12,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed              uint64         `protobuf:"varint,13,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Timestamp            string         `protobuf:"bytes,14,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TransactionsRoot     string         `protobuf:"bytes,15,opt,name=transactions_root,json=transactionsRoot,proto3" json:"transactions_root,omitempty"`
	ReceiptsRoot         string         `protobuf:"bytes,16,opt,name=receipts_root,json=receiptsRoot,proto3" json:"receipts_root,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,17,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{8}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Block) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Block) GetParentHash() string {
	if m != nil {
		return m.ParentHash
	}
	return ""
}

func (m *Block) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Block) GetMixHash() string {
	if m != nil {
		return m.MixHash
	}
	return ""
}

func (m *Block) GetLogsBloom() []byte {
	if m != nil {
		return m.LogsBloom
	}
	return nil
}

func (m *Block) GetStateRoot() string {
	if m != nil {
		return m.StateRoot
	}
	return ""
}

func (m *Block) GetMiner() string {
	if m != nil {
		return m.Miner
	}
	return ""
}

func (m *Block) GetDifficulty() uint64 {
	if m != nil {
		return m.Difficulty
	}
	return 0
}

func (m *Block) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *Block) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Block) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *Block) GetGasUsed() uint64 {
	if m != nil {
		return m.GasUsed
	}
	return 0
}

func (m *Block) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Block) GetTransactionsRoot() string {
	if m != nil {
		return m.TransactionsRoot
	}
	return ""
}

func (m *Block) GetReceiptsRoot() string {
	if m != nil {
		return m.ReceiptsRoot
	}
	return ""
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type Transaction struct {
	TxHash               string   `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	BlockHash            string   `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	From                 string   `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Hash                 string   `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	Value                string   `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	V                    string   `protobuf:"bytes,7,opt,name=v,proto3" json:"v,omitempty"`
	R                    string   `protobuf:"bytes,8,opt,name=r,proto3" json:"r,omitempty"`
	S                    string   `protobuf:"bytes,9,opt,name=s,proto3" json:"s,omitempty"`
	TransactionIndex     uint64   `protobuf:"varint,10,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"`
	Nonce                uint64   `protobuf:"varint,11,opt,name=nonce,proto3" json:"nonce,omitempty"`
	BlockNumber          uint64   `protobuf:"varint,12,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Gas                  uint64   `protobuf:"varint,13,opt,name=gas,proto3" json:"gas,omitempty"`
	GasPrice             uint64   `protobuf:"varint,14,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	Input                []byte   `protobuf:"bytes,15,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{9}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *Transaction) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *Transaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Transaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Transaction) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Transaction) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Transaction) GetV() string {
	if m != nil {
		return m.V
	}
	return ""
}

func (m *Transaction) GetR() string {
	if m != nil {
		return m.R
	}
	return ""
}

func (m *Transaction) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

func (m *Transaction) GetTransactionIndex() uint64 {
	if m != nil {
		return m.TransactionIndex
	}
	return 0
}

func (m *Transaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Transaction) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *Transaction) GetGas() uint64 {
	if m != nil {
		return m.Gas
	}
	return 0
}

func (m *Transaction) GetGasPrice() uint64 {
	if m != nil {
		return m.GasPrice
	}
	return 0
}

func (m *Transaction) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

type Receipt struct {
	BlockNumber          uint64   `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	GasUsed              uint64   `protobuf:"varint,2,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	CumulativeGasUsed    uint64   `protobuf:"varint,3,opt,name=cumulative_gas_used,json=cumulativeGasUsed,proto3" json:"cumulative_gas_used,omitempty"`
	TransactionIndex     uint64   `protobuf:"varint,4,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"`
	BlockHash            string   `protobuf:"bytes,5,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	TransactionHash      string   `protobuf:"bytes,6,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	From                 string   `protobuf:"bytes,7,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,8,opt,name=to,proto3" json:"to,omitempty"`
	ContractAddress      string   `protobuf:"bytes,9,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	Status               uint64   `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	Root                 []byte   `protobuf:"bytes,11,opt,name=root,proto3" json:"root,omitempty"`
	LogsBloom            []byte   `protobuf:"bytes,12,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	Logs                 []*Log   `protobuf:"bytes,13,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Receipt) Reset()         { *m = Receipt{} }
func (m *Receipt) String() string { return proto.CompactTextString(m) }
func (*Receipt) ProtoMessage()    {}
func (*Receipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{10}
}

func (m *Receipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Receipt.Unmarshal(m, b)
}
func (m *Receipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Receipt.Marshal(b, m, deterministic)
}
func (m *Receipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receipt.Merge(m, src)
}
func (m *Receipt) XXX_Size() int {
	return xxx_messageInfo_Receipt.Size(m)
}
func (m *Receipt) XXX_DiscardUnknown() {
	xxx_messageInfo_Receipt.DiscardUnknown(m)
}

var xxx_messageInfo_Receipt proto.InternalMessageInfo

func (m *Receipt) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *Receipt) GetGasUsed() uint64 {
	if m != nil {
		return m.GasUsed
	}
	return 0
}

func (m *Receipt) GetCumulativeGasUsed() uint64 {
	if m != nil {
		return m.CumulativeGasUsed
	}
	return 0
}

func (m *Receipt) GetTransactionIndex() uint64 {
	if m != nil {
		return m.TransactionIndex
	}
	return 0
}

func (m *Receipt) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *Receipt) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *Receipt) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Receipt) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Receipt) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *Receipt) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Receipt) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *Receipt) GetLogsBloom() []byte {
	if m != nil {
		return m.LogsBloom
	}
	return nil
}

func (m *Receipt) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

type Log struct {
	Removed              bool     `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	BlockNumber          uint64   `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TxIndex              uint64   `protobuf:"varint,3,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	BlockHash            string   `protobuf:"bytes,4,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Index                uint32   `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	Address              string   `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	TxHash               string   `protobuf:"bytes,7,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Data                 []byte   `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	Topics               []string `protobuf:"bytes,9,rep,name=topics,proto3" json:"topics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{11}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

func (m *Log) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *Log) GetTxIndex() uint64 {
	if m != nil {
		return m.TxIndex
	}
	return 0
}

func (m *Log) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *Log) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Log) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Log) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *Log) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Log) GetTopics() []string {
	if m != nil {
		return m.Topics
	}
	return nil
}

type DumpAccount struct {
	Balance              string            `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Nonce                uint64            `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Root                 string            `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	CodeHash             string            `protobuf:"bytes,4,opt,name=code_hash,json=codeHash,proto3" json:"code_hash,omitempty"`
	Code                 string            `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	Storage              map[string]string `protobuf:"bytes,6,rep,name=storage,proto3" json:"storage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DumpAccount) Reset()         { *m = DumpAccount{} }
func (m *DumpAccount) String() string { return proto.CompactTextString(m) }
func (*DumpAccount) ProtoMessage()    {}
func (*DumpAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{12}
}

func (m *DumpAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpAccount.Unmarshal(m, b)
}
func (m *DumpAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpAccount.Marshal(b, m, deterministic)
}
func (m *DumpAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpAccount.Merge(m, src)
}
func (m *DumpAccount) XXX_Size() int {
	return xxx_messageInfo_DumpAccount.Size(m)
}
func (m *DumpAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpAccount.DiscardUnknown(m)
}

var xxx_messageInfo_DumpAccount proto.InternalMessageInfo

func (m *DumpAccount) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *DumpAccount) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *DumpAccount) GetRoot() string {
	if m != nil {
		return m.Root
	}
	return ""
}

func (m *DumpAccount) GetCodeHash() string {
	if m != nil {
		return m.CodeHash
	}
	return ""
}

func (m *DumpAccount) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *DumpAccount) GetStorage() map[string]string {
	if m != nil {
		return m.Storage
	}
	return nil
}

type Dump struct {
	Root                 string                  `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Accounts             map[string]*DumpAccount `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Dump) Reset()         { *m = Dump{} }
func (m *Dump) String() string { return proto.CompactTextString(m) }
func (*Dump) ProtoMessage()    {}
func (*Dump) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{13}
}

func (m *Dump) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dump.Unmarshal(m, b)
}
func (m *Dump) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dump.Marshal(b, m, deterministic)
}
func (m *Dump) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dump.Merge(m, src)
}
func (m *Dump) XXX_Size() int {
	return xxx_messageInfo_Dump.Size(m)
}
func (m *Dump) XXX_DiscardUnknown() {
	xxx_messageInfo_Dump.DiscardUnknown(m)
}

var xxx_messageInfo_Dump proto.InternalMessageInfo

func (m *Dump) GetRoot() string {
	if m != nil {
		return m.Root
	}
	return ""
}

func (m *Dump) GetAccounts() map[string]*DumpAccount {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type BadBlockArgs struct {
	BadBlockArgs         []*BadBlockArg `protobuf:"bytes,1,rep,name=bad_block_args,json=badBlockArgs,proto3" json:"bad_block_args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BadBlockArgs) Reset()         { *m = BadBlockArgs{} }
func (m *BadBlockArgs) String() string { return proto.CompactTextString(m) }
func (*BadBlockArgs) ProtoMessage()    {}
func (*BadBlockArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{14}
}

func (m *BadBlockArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadBlockArgs.Unmarshal(m, b)
}
func (m *BadBlockArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadBlockArgs.Marshal(b, m, deterministic)
}
func (m *BadBlockArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadBlockArgs.Merge(m, src)
}
func (m *BadBlockArgs) XXX_Size() int {
	return xxx_messageInfo_BadBlockArgs.Size(m)
}
func (m *BadBlockArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_BadBlockArgs.DiscardUnknown(m)
}

var xxx_messageInfo_BadBlockArgs proto.InternalMessageInfo

func (m *BadBlockArgs) GetBadBlockArgs() []*BadBlockArg {
	if m != nil {
		return m.BadBlockArgs
	}
	return nil
}

type BadBlockArg struct {
	Hash                 string            `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Rlp                  string            `protobuf:"bytes,2,opt,name=rlp,proto3" json:"rlp,omitempty"`
	Msg                  map[string]string `protobuf:"bytes,3,rep,name=msg,proto3" json:"msg,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BadBlockArg) Reset()         { *m = BadBlockArg{} }
func (m *BadBlockArg) String() string { return proto.CompactTextString(m) }
func (*BadBlockArg) ProtoMessage()    {}
func (*BadBlockArg) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{15}
}

func (m *BadBlockArg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadBlockArg.Unmarshal(m, b)
}
func (m *BadBlockArg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadBlockArg.Marshal(b, m, deterministic)
}
func (m *BadBlockArg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadBlockArg.Merge(m, src)
}
func (m *BadBlockArg) XXX_Size() int {
	return xxx_messageInfo_BadBlockArg.Size(m)
}
func (m *BadBlockArg) XXX_DiscardUnknown() {
	xxx_messageInfo_BadBlockArg.DiscardUnknown(m)
}

var xxx_messageInfo_BadBlockArg proto.InternalMessageInfo

func (m *BadBlockArg) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BadBlockArg) GetRlp() string {
	if m != nil {
		return m.Rlp
	}
	return ""
}

func (m *BadBlockArg) GetMsg() map[string]string {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*IsOk)(nil), "protos.IsOk")
	proto.RegisterType((*BlockNumber)(nil), "protos.BlockNumber")
	proto.RegisterType((*Address)(nil), "protos.Address")
	proto.RegisterType((*Addresses)(nil), "protos.Addresses")
	proto.RegisterType((*BlockHash)(nil), "protos.BlockHash")
	proto.RegisterType((*Balance)(nil), "protos.Balance")
	proto.RegisterType((*GasPrice)(nil), "protos.GasPrice")
	proto.RegisterType((*IsFull)(nil), "protos.IsFull")
	proto.RegisterType((*Block)(nil), "protos.Block")
	proto.RegisterType((*Transaction)(nil), "protos.Transaction")
	proto.RegisterType((*Receipt)(nil), "protos.Receipt")
	proto.RegisterType((*Log)(nil), "protos.Log")
	proto.RegisterType((*DumpAccount)(nil), "protos.DumpAccount")
	proto.RegisterMapType((map[string]string)(nil), "protos.DumpAccount.StorageEntry")
	proto.RegisterType((*Dump)(nil), "protos.Dump")
	proto.RegisterMapType((map[string]*DumpAccount)(nil), "protos.Dump.AccountsEntry")
	proto.RegisterType((*BadBlockArgs)(nil), "protos.BadBlockArgs")
	proto.RegisterType((*BadBlockArg)(nil), "protos.BadBlockArg")
	proto.RegisterMapType((map[string]string)(nil), "protos.BadBlockArg.MsgEntry")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 1121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xcb, 0x72, 0xe3, 0x44,
	0x17, 0x2e, 0x59, 0xf2, 0x45, 0xc7, 0xca, 0xad, 0x93, 0x9a, 0x5f, 0x7f, 0x12, 0x98, 0x8c, 0x66,
	0x41, 0x02, 0x94, 0x87, 0x82, 0xaa, 0x01, 0xb2, 0x4b, 0x6a, 0x60, 0x48, 0x55, 0x60, 0xa6, 0x04,
	0x6c, 0xd8, 0xb8, 0xda, 0x52, 0x47, 0xe9, 0xb2, 0xa4, 0x56, 0xa9, 0x5b, 0x29, 0x87, 0x77, 0xe0,
	0x09, 0xd8, 0xb2, 0xe1, 0xcd, 0xd8, 0xb2, 0x65, 0x45, 0xf5, 0x69, 0xc9, 0x6e, 0x7b, 0x3c, 0x0b,
	0x36, 0xf6, 0xb9, 0xb5, 0xce, 0xe5, 0xfb, 0xfa, 0x48, 0x10, 0x24, 0xa2, 0x28, 0x44, 0x39, 0xa9,
	0x6a, 0xa1, 0x04, 0x19, 0xe0, 0x9f, 0x3c, 0x3e, 0xcd, 0x84, 0xc8, 0x72, 0xf6, 0x82, 0x56, 0xfc,
	0x05, 0x2d, 0x4b, 0xa1, 0xa8, 0xe2, 0xa2, 0x94, 0x26, 0x2a, 0x3a, 0x01, 0xef, 0x46, 0xbe, 0x99,
	0x93, 0x43, 0xe8, 0x73, 0x39, 0x15, 0xf3, 0xd0, 0x39, 0x73, 0xce, 0x47, 0xb1, 0xc7, 0xe5, 0x9b,
	0x79, 0xf4, 0x19, 0x8c, 0xaf, 0x73, 0x91, 0xcc, 0x7f, 0x68, 0x8a, 0x19, 0xab, 0xc9, 0x33, 0x08,
	0x66, 0x5a, 0x9d, 0x96, 0xa8, 0x63, 0xa8, 0x1b, 0x8f, 0x67, 0xab, 0x90, 0xe8, 0x39, 0x0c, 0xaf,
	0xd2, 0xb4, 0x66, 0x52, 0x92, 0x10, 0x86, 0xd4, 0x88, 0x18, 0xe8, 0xc7, 0x9d, 0x1a, 0x5d, 0x80,
	0xdf, 0x06, 0x31, 0x49, 0x4e, 0xc1, 0xa7, 0x9d, 0x12, 0x3a, 0x67, 0xee, 0xb9, 0x1f, 0xaf, 0x0c,
	0xd1, 0xc7, 0xe0, 0x63, 0x05, 0xdf, 0x51, 0x79, 0x4f, 0x3e, 0x00, 0x30, 0xf9, 0xef, 0xa9, 0xbc,
	0x6f, 0x1f, 0xea, 0xcf, 0x3a, 0xb7, 0xce, 0x7d, 0x4d, 0x73, 0x5a, 0x26, 0x4c, 0xe7, 0x9e, 0x19,
	0xb1, 0xcb, 0xdd, 0xaa, 0xd1, 0x47, 0x30, 0x7a, 0x4d, 0xe5, 0xdb, 0x9a, 0x27, 0x8c, 0x9c, 0x80,
	0x9f, 0x51, 0x39, 0xad, 0xb4, 0x82, 0x71, 0x41, 0x3c, 0xca, 0x5a, 0x67, 0xf4, 0x0c, 0x06, 0x37,
	0xf2, 0xdb, 0x26, 0xcf, 0xc9, 0xff, 0x60, 0xc8, 0xe5, 0xf4, 0xae, 0xc9, 0xf3, 0x76, 0x38, 0x03,
	0x8e, 0x8e, 0xe8, 0x37, 0x0f, 0xfa, 0x58, 0x1d, 0x79, 0x02, 0x03, 0x6b, 0x26, 0x5e, 0xdc, 0x6a,
	0x84, 0x80, 0x87, 0xb5, 0xf6, 0xb0, 0x08, 0x94, 0xc9, 0x53, 0x18, 0x57, 0xb4, 0x66, 0xa5, 0x32,
	0x6d, 0xb8, 0xe8, 0x02, 0x63, 0xc2, 0x36, 0x8f, 0xa0, 0x5f, 0x0a, 0x5d, 0xba, 0x87, 0xcf, 0x32,
	0x0a, 0xf9, 0x3f, 0x8c, 0x0a, 0xbe, 0x30, 0x67, 0xfa, 0xa6, 0xa7, 0x82, 0x2f, 0xba, 0xb9, 0xe4,
	0x22, 0x93, 0xd3, 0x59, 0x2e, 0x44, 0x11, 0x0e, 0xb0, 0x11, 0x5f, 0x5b, 0xae, 0xb5, 0x41, 0xbb,
	0xa5, 0xa2, 0x8a, 0x4d, 0x6b, 0x21, 0x54, 0x38, 0x34, 0x63, 0x43, 0x4b, 0x2c, 0x84, 0xd2, 0xe9,
	0x0a, 0x5e, 0xb2, 0x3a, 0x1c, 0xa1, 0xc7, 0x28, 0xe4, 0x43, 0x80, 0x94, 0xdf, 0xdd, 0xf1, 0xa4,
	0xc9, 0xd5, 0x63, 0xe8, 0x63, 0x25, 0x96, 0x45, 0x3f, 0x94, 0x2d, 0x54, 0x4d, 0xa7, 0x29, 0x55,
	0x34, 0x04, 0x93, 0x13, 0x2d, 0xaf, 0xa8, 0xa2, 0xba, 0x71, 0xc9, 0x7f, 0x65, 0xe1, 0x18, 0x0f,
	0xa2, 0xdc, 0x8d, 0x3b, 0xe7, 0x05, 0x57, 0x61, 0x80, 0x0e, 0x3d, 0xee, 0x5b, 0xad, 0xeb, 0xf6,
	0xb4, 0xb3, 0x91, 0x2c, 0x0d, 0x77, 0xd0, 0x37, 0xcc, 0xa8, 0xfc, 0x59, 0xb2, 0x54, 0x33, 0x44,
	0xf1, 0x82, 0x49, 0x45, 0x8b, 0x2a, 0xdc, 0x35, 0xe5, 0x2f, 0x0d, 0xe4, 0x13, 0x38, 0x50, 0x35,
	0x2d, 0x25, 0x4d, 0x90, 0xd6, 0xa6, 0xc9, 0x3d, 0x8c, 0xda, 0xb7, 0x1d, 0xd8, 0xeb, 0x73, 0xd8,
	0xa9, 0x59, 0xc2, 0x78, 0xa5, 0xda, 0xc0, 0x7d, 0x0c, 0x0c, 0x3a, 0x23, 0x06, 0x7d, 0x09, 0x81,
	0x7d, 0x30, 0x3c, 0x38, 0x73, 0xcf, 0xc7, 0x9f, 0x1f, 0x9a, 0x0b, 0x23, 0x27, 0x3f, 0xad, 0x7c,
	0xf1, 0x5a, 0x60, 0xf4, 0x57, 0x0f, 0xc6, 0x96, 0x57, 0x13, 0x47, 0x2d, 0x6c, 0xb2, 0x0e, 0xd4,
	0x62, 0x0b, 0x91, 0x7b, 0x1b, 0x44, 0xd6, 0xc3, 0xbb, 0xab, 0x45, 0xd1, 0x52, 0x03, 0x65, 0xb2,
	0x0b, 0x3d, 0x25, 0x90, 0x11, 0x7e, 0xdc, 0x53, 0x62, 0xc9, 0xac, 0xbe, 0xc5, 0xac, 0x23, 0xe8,
	0x3f, 0xd0, 0xbc, 0x61, 0x48, 0x01, 0x3f, 0x36, 0x0a, 0x09, 0xc0, 0x79, 0x68, 0x51, 0x77, 0x1e,
	0xb4, 0xd6, 0x21, 0xed, 0xd4, 0x5a, 0x93, 0x08, 0xae, 0x1f, 0x3b, 0x72, 0x63, 0x94, 0x53, 0x5e,
	0xa6, 0x6c, 0x81, 0xd0, 0x7a, 0x6b, 0xa3, 0xbc, 0xd1, 0xf6, 0x15, 0x4b, 0xc7, 0x36, 0x4b, 0x37,
	0x57, 0x84, 0x81, 0xd9, 0x5e, 0x11, 0x64, 0x1f, 0xdc, 0x8c, 0xca, 0x16, 0x64, 0x2d, 0xae, 0xdf,
	0xc3, 0xdd, 0x25, 0x31, 0xcc, 0x25, 0x3d, 0x82, 0x3e, 0x2f, 0xab, 0xc6, 0x60, 0x1a, 0xc4, 0x46,
	0x89, 0xfe, 0x74, 0x61, 0x18, 0x1b, 0xd0, 0xb6, 0xae, 0xa5, 0x8d, 0x9c, 0x36, 0xbb, 0x7a, 0xeb,
	0xec, 0x9a, 0xc0, 0x61, 0xd2, 0x14, 0x4d, 0x4e, 0x15, 0x7f, 0x60, 0xd3, 0x65, 0x94, 0x8b, 0x51,
	0x07, 0x2b, 0xd7, 0xeb, 0x36, 0x7e, 0xeb, 0x90, 0xbc, 0xf7, 0x0c, 0x69, 0x1d, 0xe8, 0xfe, 0x26,
	0xd0, 0x17, 0x60, 0x1f, 0x31, 0x41, 0x06, 0xbb, 0x3d, 0xcb, 0xbe, 0xc6, 0x89, 0xe1, 0x3b, 0x9c,
	0x18, 0x2d, 0x39, 0x71, 0x01, 0xfb, 0x89, 0x28, 0x55, 0x4d, 0x13, 0x35, 0xed, 0x56, 0xaf, 0x01,
	0x77, 0xaf, 0xb3, 0x77, 0xcb, 0xf9, 0x09, 0x0c, 0xf4, 0x06, 0x68, 0x64, 0x8b, 0x6f, 0xab, 0xe9,
	0x34, 0x78, 0x2f, 0xc6, 0x38, 0x6c, 0x94, 0x37, 0xd6, 0x4b, 0xb0, 0xb9, 0x5e, 0x9e, 0x82, 0xa7,
	0x95, 0x70, 0x07, 0xaf, 0xc9, 0xb8, 0xbb, 0x26, 0xb7, 0x22, 0x8b, 0xd1, 0x11, 0xfd, 0xed, 0x80,
	0x7b, 0x2b, 0x32, 0xbd, 0x94, 0x6b, 0x56, 0x88, 0x07, 0x96, 0xb6, 0x7b, 0xb4, 0x53, 0xdf, 0x41,
	0xb0, 0xb7, 0x15, 0x41, 0xb5, 0x68, 0xa7, 0x6d, 0xb0, 0x19, 0xaa, 0xc5, 0xb6, 0x21, 0x7b, 0x9b,
	0x43, 0x46, 0x02, 0xe9, 0x63, 0x7a, 0xfc, 0x3b, 0xb1, 0x51, 0xec, 0xb7, 0xd3, 0x60, 0xed, 0xed,
	0x64, 0xdf, 0xda, 0xe1, 0xda, 0xad, 0x25, 0xe0, 0xe1, 0xb2, 0x1b, 0x99, 0xd9, 0x68, 0x59, 0xcf,
	0x51, 0x89, 0x8a, 0x27, 0x7a, 0xd0, 0x2e, 0xc6, 0xa2, 0x16, 0xfd, 0xe3, 0xc0, 0xf8, 0x55, 0x53,
	0x54, 0x57, 0x49, 0x22, 0x9a, 0x52, 0xbd, 0xff, 0x85, 0xb4, 0xba, 0x47, 0x3d, 0xfb, 0x1e, 0x75,
	0x38, 0xb4, 0x2b, 0x00, 0x71, 0x38, 0x01, 0x3f, 0x11, 0x29, 0xb3, 0xdb, 0x1c, 0x69, 0x43, 0x57,
	0x9c, 0x96, 0xbb, 0x7d, 0xa0, 0x65, 0x72, 0x09, 0x43, 0xa9, 0x44, 0x4d, 0x33, 0xbd, 0x11, 0x34,
	0x38, 0x67, 0x1d, 0x38, 0x56, 0x69, 0x93, 0x1f, 0x4d, 0xc8, 0x37, 0xa5, 0xaa, 0x1f, 0xe3, 0xee,
	0xc0, 0xf1, 0x25, 0x04, 0xb6, 0x43, 0xdf, 0xda, 0x39, 0x7b, 0x6c, 0x8b, 0xd7, 0xe2, 0x6a, 0xdb,
	0xf4, 0xac, 0x6d, 0x73, 0xd9, 0xfb, 0xca, 0x89, 0xfe, 0x70, 0xc0, 0xd3, 0x19, 0x96, 0x5d, 0x38,
	0x56, 0x17, 0x2f, 0x61, 0x44, 0x4d, 0x66, 0x19, 0xf6, 0xb0, 0xaa, 0x63, 0xbb, 0xaa, 0x49, 0x5b,
	0x96, 0x34, 0xf5, 0x2c, 0x63, 0x8f, 0xdf, 0xc2, 0xce, 0x9a, 0x6b, 0x4b, 0x45, 0x17, 0x76, 0x45,
	0xd6, 0xc6, 0xb6, 0xba, 0xb5, 0xcb, 0xbc, 0x81, 0xe0, 0x9a, 0xa6, 0xf8, 0x02, 0xbf, 0xaa, 0x33,
	0x49, 0xbe, 0x86, 0xdd, 0x19, 0x4d, 0xa7, 0x86, 0x4b, 0xb4, 0xce, 0xcc, 0xe7, 0x88, 0xf5, 0x1c,
	0x2b, 0x3a, 0x0e, 0x66, 0xd6, 0xd1, 0xe8, 0x77, 0x07, 0xc6, 0x96, 0x77, 0xb9, 0x9d, 0x1d, 0x6b,
	0x3b, 0xef, 0x83, 0x5b, 0xe7, 0x55, 0x3b, 0x2d, 0x2d, 0x92, 0x09, 0xb8, 0x85, 0xcc, 0x42, 0x17,
	0xb3, 0x9c, 0x6e, 0xc9, 0x32, 0xf9, 0x5e, 0x66, 0x66, 0x0e, 0x3a, 0xf0, 0xf8, 0x25, 0x8c, 0x3a,
	0xc3, 0x7f, 0xc1, 0xe3, 0xfa, 0x53, 0x88, 0x44, 0x9d, 0x4d, 0x66, 0x5c, 0xcd, 0x9a, 0x64, 0xce,
	0xd4, 0x24, 0xa9, 0x92, 0x7b, 0xca, 0xcb, 0x89, 0xf9, 0x35, 0x79, 0x7f, 0x69, 0xbf, 0x17, 0x67,
	0xe6, 0xff, 0x8b, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x30, 0x4c, 0x9b, 0x8f, 0x4e, 0x0a, 0x00,
	0x00,
}
