// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/common/common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// IsOk return status
type IsOk struct {
	IsOk                 bool     `protobuf:"varint,1,opt,name=isOk,proto3" json:"isOk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsOk) Reset()         { *m = IsOk{} }
func (m *IsOk) String() string { return proto.CompactTextString(m) }
func (*IsOk) ProtoMessage()    {}
func (*IsOk) Descriptor() ([]byte, []int) {
	return fileDescriptor_413c02bc47c81d3d, []int{0}
}

func (m *IsOk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsOk.Unmarshal(m, b)
}
func (m *IsOk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsOk.Marshal(b, m, deterministic)
}
func (m *IsOk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsOk.Merge(m, src)
}
func (m *IsOk) XXX_Size() int {
	return xxx_messageInfo_IsOk.Size(m)
}
func (m *IsOk) XXX_DiscardUnknown() {
	xxx_messageInfo_IsOk.DiscardUnknown(m)
}

var xxx_messageInfo_IsOk proto.InternalMessageInfo

func (m *IsOk) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

type Code struct {
	Code                 []byte   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Code) Reset()         { *m = Code{} }
func (m *Code) String() string { return proto.CompactTextString(m) }
func (*Code) ProtoMessage()    {}
func (*Code) Descriptor() ([]byte, []int) {
	return fileDescriptor_413c02bc47c81d3d, []int{1}
}

func (m *Code) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Code.Unmarshal(m, b)
}
func (m *Code) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Code.Marshal(b, m, deterministic)
}
func (m *Code) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Code.Merge(m, src)
}
func (m *Code) XXX_Size() int {
	return xxx_messageInfo_Code.Size(m)
}
func (m *Code) XXX_DiscardUnknown() {
	xxx_messageInfo_Code.DiscardUnknown(m)
}

var xxx_messageInfo_Code proto.InternalMessageInfo

func (m *Code) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

type BlockNumber struct {
	BlockNumber          int64    `protobuf:"varint,1,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockNumber) Reset()         { *m = BlockNumber{} }
func (m *BlockNumber) String() string { return proto.CompactTextString(m) }
func (*BlockNumber) ProtoMessage()    {}
func (*BlockNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_413c02bc47c81d3d, []int{2}
}

func (m *BlockNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockNumber.Unmarshal(m, b)
}
func (m *BlockNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockNumber.Marshal(b, m, deterministic)
}
func (m *BlockNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockNumber.Merge(m, src)
}
func (m *BlockNumber) XXX_Size() int {
	return xxx_messageInfo_BlockNumber.Size(m)
}
func (m *BlockNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockNumber.DiscardUnknown(m)
}

var xxx_messageInfo_BlockNumber proto.InternalMessageInfo

func (m *BlockNumber) GetBlockNumber() int64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

type Address struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_413c02bc47c81d3d, []int{3}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Addresses struct {
	Addresses            []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Addresses) Reset()         { *m = Addresses{} }
func (m *Addresses) String() string { return proto.CompactTextString(m) }
func (*Addresses) ProtoMessage()    {}
func (*Addresses) Descriptor() ([]byte, []int) {
	return fileDescriptor_413c02bc47c81d3d, []int{4}
}

func (m *Addresses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Addresses.Unmarshal(m, b)
}
func (m *Addresses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Addresses.Marshal(b, m, deterministic)
}
func (m *Addresses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Addresses.Merge(m, src)
}
func (m *Addresses) XXX_Size() int {
	return xxx_messageInfo_Addresses.Size(m)
}
func (m *Addresses) XXX_DiscardUnknown() {
	xxx_messageInfo_Addresses.DiscardUnknown(m)
}

var xxx_messageInfo_Addresses proto.InternalMessageInfo

func (m *Addresses) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type BlockHash struct {
	BlockHash            string   `protobuf:"bytes,1,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHash) Reset()         { *m = BlockHash{} }
func (m *BlockHash) String() string { return proto.CompactTextString(m) }
func (*BlockHash) ProtoMessage()    {}
func (*BlockHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_413c02bc47c81d3d, []int{5}
}

func (m *BlockHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHash.Unmarshal(m, b)
}
func (m *BlockHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHash.Marshal(b, m, deterministic)
}
func (m *BlockHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHash.Merge(m, src)
}
func (m *BlockHash) XXX_Size() int {
	return xxx_messageInfo_BlockHash.Size(m)
}
func (m *BlockHash) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHash.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHash proto.InternalMessageInfo

func (m *BlockHash) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

type Hash struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hash) Reset()         { *m = Hash{} }
func (m *Hash) String() string { return proto.CompactTextString(m) }
func (*Hash) ProtoMessage()    {}
func (*Hash) Descriptor() ([]byte, []int) {
	return fileDescriptor_413c02bc47c81d3d, []int{6}
}

func (m *Hash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hash.Unmarshal(m, b)
}
func (m *Hash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hash.Marshal(b, m, deterministic)
}
func (m *Hash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hash.Merge(m, src)
}
func (m *Hash) XXX_Size() int {
	return xxx_messageInfo_Hash.Size(m)
}
func (m *Hash) XXX_DiscardUnknown() {
	xxx_messageInfo_Hash.DiscardUnknown(m)
}

var xxx_messageInfo_Hash proto.InternalMessageInfo

func (m *Hash) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type Balance struct {
	Balance              string   `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Balance) Reset()         { *m = Balance{} }
func (m *Balance) String() string { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()    {}
func (*Balance) Descriptor() ([]byte, []int) {
	return fileDescriptor_413c02bc47c81d3d, []int{7}
}

func (m *Balance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Balance.Unmarshal(m, b)
}
func (m *Balance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Balance.Marshal(b, m, deterministic)
}
func (m *Balance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Balance.Merge(m, src)
}
func (m *Balance) XXX_Size() int {
	return xxx_messageInfo_Balance.Size(m)
}
func (m *Balance) XXX_DiscardUnknown() {
	xxx_messageInfo_Balance.DiscardUnknown(m)
}

var xxx_messageInfo_Balance proto.InternalMessageInfo

func (m *Balance) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

type GasPrice struct {
	GasPrice             int64    `protobuf:"varint,1,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GasPrice) Reset()         { *m = GasPrice{} }
func (m *GasPrice) String() string { return proto.CompactTextString(m) }
func (*GasPrice) ProtoMessage()    {}
func (*GasPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_413c02bc47c81d3d, []int{8}
}

func (m *GasPrice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GasPrice.Unmarshal(m, b)
}
func (m *GasPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GasPrice.Marshal(b, m, deterministic)
}
func (m *GasPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GasPrice.Merge(m, src)
}
func (m *GasPrice) XXX_Size() int {
	return xxx_messageInfo_GasPrice.Size(m)
}
func (m *GasPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_GasPrice.DiscardUnknown(m)
}

var xxx_messageInfo_GasPrice proto.InternalMessageInfo

func (m *GasPrice) GetGasPrice() int64 {
	if m != nil {
		return m.GasPrice
	}
	return 0
}

type IsFull struct {
	IsFull               bool     `protobuf:"varint,1,opt,name=isFull,proto3" json:"isFull,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsFull) Reset()         { *m = IsFull{} }
func (m *IsFull) String() string { return proto.CompactTextString(m) }
func (*IsFull) ProtoMessage()    {}
func (*IsFull) Descriptor() ([]byte, []int) {
	return fileDescriptor_413c02bc47c81d3d, []int{9}
}

func (m *IsFull) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsFull.Unmarshal(m, b)
}
func (m *IsFull) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsFull.Marshal(b, m, deterministic)
}
func (m *IsFull) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsFull.Merge(m, src)
}
func (m *IsFull) XXX_Size() int {
	return xxx_messageInfo_IsFull.Size(m)
}
func (m *IsFull) XXX_DiscardUnknown() {
	xxx_messageInfo_IsFull.DiscardUnknown(m)
}

var xxx_messageInfo_IsFull proto.InternalMessageInfo

func (m *IsFull) GetIsFull() bool {
	if m != nil {
		return m.IsFull
	}
	return false
}

type Block struct {
	Number               uint64         `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Hash                 string         `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	ParentHash           string         `protobuf:"bytes,3,opt,name=parentHash,proto3" json:"parentHash,omitempty"`
	Nonce                uint64         `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	MixHash              string         `protobuf:"bytes,5,opt,name=mixHash,proto3" json:"mixHash,omitempty"`
	LogsBloom            []byte         `protobuf:"bytes,6,opt,name=logsBloom,proto3" json:"logsBloom,omitempty"`
	StateRoot            string         `protobuf:"bytes,7,opt,name=stateRoot,proto3" json:"stateRoot,omitempty"`
	Miner                string         `protobuf:"bytes,8,opt,name=miner,proto3" json:"miner,omitempty"`
	Difficulty           uint64         `protobuf:"varint,9,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	ExtraData            []byte         `protobuf:"bytes,10,opt,name=extraData,proto3" json:"extraData,omitempty"`
	Size                 uint64         `protobuf:"varint,11,opt,name=size,proto3" json:"size,omitempty"`
	GasLimit             uint64         `protobuf:"varint,12,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	GasUsed              uint64         `protobuf:"varint,13,opt,name=gasUsed,proto3" json:"gasUsed,omitempty"`
	Timestamp            string         `protobuf:"bytes,14,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TransactionsRoot     string         `protobuf:"bytes,15,opt,name=transactionsRoot,proto3" json:"transactionsRoot,omitempty"`
	ReceiptsRoot         string         `protobuf:"bytes,16,opt,name=receiptsRoot,proto3" json:"receiptsRoot,omitempty"`
	Error                string         `protobuf:"bytes,17,opt,name=error,proto3" json:"error,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,18,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_413c02bc47c81d3d, []int{10}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Block) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Block) GetParentHash() string {
	if m != nil {
		return m.ParentHash
	}
	return ""
}

func (m *Block) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Block) GetMixHash() string {
	if m != nil {
		return m.MixHash
	}
	return ""
}

func (m *Block) GetLogsBloom() []byte {
	if m != nil {
		return m.LogsBloom
	}
	return nil
}

func (m *Block) GetStateRoot() string {
	if m != nil {
		return m.StateRoot
	}
	return ""
}

func (m *Block) GetMiner() string {
	if m != nil {
		return m.Miner
	}
	return ""
}

func (m *Block) GetDifficulty() uint64 {
	if m != nil {
		return m.Difficulty
	}
	return 0
}

func (m *Block) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *Block) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Block) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *Block) GetGasUsed() uint64 {
	if m != nil {
		return m.GasUsed
	}
	return 0
}

func (m *Block) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Block) GetTransactionsRoot() string {
	if m != nil {
		return m.TransactionsRoot
	}
	return ""
}

func (m *Block) GetReceiptsRoot() string {
	if m != nil {
		return m.ReceiptsRoot
	}
	return ""
}

func (m *Block) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type Transaction struct {
	TxHash               string   `protobuf:"bytes,1,opt,name=txHash,proto3" json:"txHash,omitempty"`
	BlockHash            string   `protobuf:"bytes,2,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	From                 string   `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Hash                 string   `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	Value                string   `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	V                    string   `protobuf:"bytes,7,opt,name=v,proto3" json:"v,omitempty"`
	R                    string   `protobuf:"bytes,8,opt,name=r,proto3" json:"r,omitempty"`
	S                    string   `protobuf:"bytes,9,opt,name=s,proto3" json:"s,omitempty"`
	TransactionIndex     uint64   `protobuf:"varint,10,opt,name=transactionIndex,proto3" json:"transactionIndex,omitempty"`
	Nonce                uint64   `protobuf:"varint,11,opt,name=nonce,proto3" json:"nonce,omitempty"`
	BlockNumber          uint64   `protobuf:"varint,12,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	Gas                  uint64   `protobuf:"varint,13,opt,name=gas,proto3" json:"gas,omitempty"`
	GasPrice             uint64   `protobuf:"varint,14,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	Input                []byte   `protobuf:"bytes,15,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_413c02bc47c81d3d, []int{11}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *Transaction) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *Transaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Transaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Transaction) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Transaction) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Transaction) GetV() string {
	if m != nil {
		return m.V
	}
	return ""
}

func (m *Transaction) GetR() string {
	if m != nil {
		return m.R
	}
	return ""
}

func (m *Transaction) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

func (m *Transaction) GetTransactionIndex() uint64 {
	if m != nil {
		return m.TransactionIndex
	}
	return 0
}

func (m *Transaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Transaction) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *Transaction) GetGas() uint64 {
	if m != nil {
		return m.Gas
	}
	return 0
}

func (m *Transaction) GetGasPrice() uint64 {
	if m != nil {
		return m.GasPrice
	}
	return 0
}

func (m *Transaction) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

type Receipt struct {
	BlockNumber          uint64   `protobuf:"varint,1,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	GasUsed              uint64   `protobuf:"varint,2,opt,name=gasUsed,proto3" json:"gasUsed,omitempty"`
	CumulativeGasUsed    uint64   `protobuf:"varint,3,opt,name=cumulativeGasUsed,proto3" json:"cumulativeGasUsed,omitempty"`
	TransactionIndex     uint64   `protobuf:"varint,4,opt,name=transactionIndex,proto3" json:"transactionIndex,omitempty"`
	BlockHash            string   `protobuf:"bytes,5,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	TransactionHash      string   `protobuf:"bytes,6,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	From                 string   `protobuf:"bytes,7,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,8,opt,name=to,proto3" json:"to,omitempty"`
	ContractAddress      string   `protobuf:"bytes,9,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
	Status               uint64   `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	Root                 []byte   `protobuf:"bytes,11,opt,name=root,proto3" json:"root,omitempty"`
	LogsBloom            []byte   `protobuf:"bytes,12,opt,name=logsBloom,proto3" json:"logsBloom,omitempty"`
	Logs                 []*Log   `protobuf:"bytes,13,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Receipt) Reset()         { *m = Receipt{} }
func (m *Receipt) String() string { return proto.CompactTextString(m) }
func (*Receipt) ProtoMessage()    {}
func (*Receipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_413c02bc47c81d3d, []int{12}
}

func (m *Receipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Receipt.Unmarshal(m, b)
}
func (m *Receipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Receipt.Marshal(b, m, deterministic)
}
func (m *Receipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receipt.Merge(m, src)
}
func (m *Receipt) XXX_Size() int {
	return xxx_messageInfo_Receipt.Size(m)
}
func (m *Receipt) XXX_DiscardUnknown() {
	xxx_messageInfo_Receipt.DiscardUnknown(m)
}

var xxx_messageInfo_Receipt proto.InternalMessageInfo

func (m *Receipt) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *Receipt) GetGasUsed() uint64 {
	if m != nil {
		return m.GasUsed
	}
	return 0
}

func (m *Receipt) GetCumulativeGasUsed() uint64 {
	if m != nil {
		return m.CumulativeGasUsed
	}
	return 0
}

func (m *Receipt) GetTransactionIndex() uint64 {
	if m != nil {
		return m.TransactionIndex
	}
	return 0
}

func (m *Receipt) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *Receipt) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *Receipt) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Receipt) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Receipt) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *Receipt) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Receipt) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *Receipt) GetLogsBloom() []byte {
	if m != nil {
		return m.LogsBloom
	}
	return nil
}

func (m *Receipt) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

type Log struct {
	Removed              bool     `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	BlockNumber          uint64   `protobuf:"varint,2,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	TxIndex              uint64   `protobuf:"varint,3,opt,name=txIndex,proto3" json:"txIndex,omitempty"`
	BlockHash            string   `protobuf:"bytes,4,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	Index                uint32   `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	Address              string   `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	TxHash               string   `protobuf:"bytes,7,opt,name=txHash,proto3" json:"txHash,omitempty"`
	Data                 []byte   `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	Topics               []string `protobuf:"bytes,9,rep,name=topics,proto3" json:"topics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_413c02bc47c81d3d, []int{13}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

func (m *Log) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *Log) GetTxIndex() uint64 {
	if m != nil {
		return m.TxIndex
	}
	return 0
}

func (m *Log) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *Log) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Log) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Log) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *Log) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Log) GetTopics() []string {
	if m != nil {
		return m.Topics
	}
	return nil
}

type DumpAccount struct {
	Balance              string            `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Nonce                uint64            `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Root                 string            `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	CodeHash             string            `protobuf:"bytes,4,opt,name=code_hash,json=codeHash,proto3" json:"code_hash,omitempty"`
	Code                 string            `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	Storage              map[string]string `protobuf:"bytes,6,rep,name=storage,proto3" json:"storage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DumpAccount) Reset()         { *m = DumpAccount{} }
func (m *DumpAccount) String() string { return proto.CompactTextString(m) }
func (*DumpAccount) ProtoMessage()    {}
func (*DumpAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_413c02bc47c81d3d, []int{14}
}

func (m *DumpAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpAccount.Unmarshal(m, b)
}
func (m *DumpAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpAccount.Marshal(b, m, deterministic)
}
func (m *DumpAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpAccount.Merge(m, src)
}
func (m *DumpAccount) XXX_Size() int {
	return xxx_messageInfo_DumpAccount.Size(m)
}
func (m *DumpAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpAccount.DiscardUnknown(m)
}

var xxx_messageInfo_DumpAccount proto.InternalMessageInfo

func (m *DumpAccount) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *DumpAccount) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *DumpAccount) GetRoot() string {
	if m != nil {
		return m.Root
	}
	return ""
}

func (m *DumpAccount) GetCodeHash() string {
	if m != nil {
		return m.CodeHash
	}
	return ""
}

func (m *DumpAccount) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *DumpAccount) GetStorage() map[string]string {
	if m != nil {
		return m.Storage
	}
	return nil
}

type Dump struct {
	Root                 string                  `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Accounts             map[string]*DumpAccount `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Dump) Reset()         { *m = Dump{} }
func (m *Dump) String() string { return proto.CompactTextString(m) }
func (*Dump) ProtoMessage()    {}
func (*Dump) Descriptor() ([]byte, []int) {
	return fileDescriptor_413c02bc47c81d3d, []int{15}
}

func (m *Dump) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dump.Unmarshal(m, b)
}
func (m *Dump) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dump.Marshal(b, m, deterministic)
}
func (m *Dump) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dump.Merge(m, src)
}
func (m *Dump) XXX_Size() int {
	return xxx_messageInfo_Dump.Size(m)
}
func (m *Dump) XXX_DiscardUnknown() {
	xxx_messageInfo_Dump.DiscardUnknown(m)
}

var xxx_messageInfo_Dump proto.InternalMessageInfo

func (m *Dump) GetRoot() string {
	if m != nil {
		return m.Root
	}
	return ""
}

func (m *Dump) GetAccounts() map[string]*DumpAccount {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type BadBlockArgs struct {
	BadBlockArgs         []*BadBlockArg `protobuf:"bytes,1,rep,name=badBlockArgs,proto3" json:"badBlockArgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BadBlockArgs) Reset()         { *m = BadBlockArgs{} }
func (m *BadBlockArgs) String() string { return proto.CompactTextString(m) }
func (*BadBlockArgs) ProtoMessage()    {}
func (*BadBlockArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_413c02bc47c81d3d, []int{16}
}

func (m *BadBlockArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadBlockArgs.Unmarshal(m, b)
}
func (m *BadBlockArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadBlockArgs.Marshal(b, m, deterministic)
}
func (m *BadBlockArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadBlockArgs.Merge(m, src)
}
func (m *BadBlockArgs) XXX_Size() int {
	return xxx_messageInfo_BadBlockArgs.Size(m)
}
func (m *BadBlockArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_BadBlockArgs.DiscardUnknown(m)
}

var xxx_messageInfo_BadBlockArgs proto.InternalMessageInfo

func (m *BadBlockArgs) GetBadBlockArgs() []*BadBlockArg {
	if m != nil {
		return m.BadBlockArgs
	}
	return nil
}

type BadBlockArg struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Rlp                  string   `protobuf:"bytes,2,opt,name=rlp,proto3" json:"rlp,omitempty"`
	Block                *Block   `protobuf:"bytes,3,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BadBlockArg) Reset()         { *m = BadBlockArg{} }
func (m *BadBlockArg) String() string { return proto.CompactTextString(m) }
func (*BadBlockArg) ProtoMessage()    {}
func (*BadBlockArg) Descriptor() ([]byte, []int) {
	return fileDescriptor_413c02bc47c81d3d, []int{17}
}

func (m *BadBlockArg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadBlockArg.Unmarshal(m, b)
}
func (m *BadBlockArg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadBlockArg.Marshal(b, m, deterministic)
}
func (m *BadBlockArg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadBlockArg.Merge(m, src)
}
func (m *BadBlockArg) XXX_Size() int {
	return xxx_messageInfo_BadBlockArg.Size(m)
}
func (m *BadBlockArg) XXX_DiscardUnknown() {
	xxx_messageInfo_BadBlockArg.DiscardUnknown(m)
}

var xxx_messageInfo_BadBlockArg proto.InternalMessageInfo

func (m *BadBlockArg) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BadBlockArg) GetRlp() string {
	if m != nil {
		return m.Rlp
	}
	return ""
}

func (m *BadBlockArg) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

// - startingBlock: block number this node started to synchronise from
// - currentBlock:  block number this node is currently importing
// - highestBlock:  block number of the highest block header this node has received from peers
// - pulledStates:  number of state entries processed until now
// - knownStates:   number of known state entries that still need to be pulled
type SyncingInfo struct {
	IsSyncing            bool     `protobuf:"varint,1,opt,name=isSyncing,proto3" json:"isSyncing,omitempty"`
	StartBlock           uint64   `protobuf:"varint,2,opt,name=startBlock,proto3" json:"startBlock,omitempty"`
	CurrentBlock         uint64   `protobuf:"varint,3,opt,name=currentBlock,proto3" json:"currentBlock,omitempty"`
	HighestBlock         uint64   `protobuf:"varint,4,opt,name=highestBlock,proto3" json:"highestBlock,omitempty"`
	PulledStates         uint64   `protobuf:"varint,5,opt,name=pulledStates,proto3" json:"pulledStates,omitempty"`
	KnownStates          uint64   `protobuf:"varint,6,opt,name=knownStates,proto3" json:"knownStates,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncingInfo) Reset()         { *m = SyncingInfo{} }
func (m *SyncingInfo) String() string { return proto.CompactTextString(m) }
func (*SyncingInfo) ProtoMessage()    {}
func (*SyncingInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_413c02bc47c81d3d, []int{18}
}

func (m *SyncingInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncingInfo.Unmarshal(m, b)
}
func (m *SyncingInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncingInfo.Marshal(b, m, deterministic)
}
func (m *SyncingInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncingInfo.Merge(m, src)
}
func (m *SyncingInfo) XXX_Size() int {
	return xxx_messageInfo_SyncingInfo.Size(m)
}
func (m *SyncingInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncingInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SyncingInfo proto.InternalMessageInfo

func (m *SyncingInfo) GetIsSyncing() bool {
	if m != nil {
		return m.IsSyncing
	}
	return false
}

func (m *SyncingInfo) GetStartBlock() uint64 {
	if m != nil {
		return m.StartBlock
	}
	return 0
}

func (m *SyncingInfo) GetCurrentBlock() uint64 {
	if m != nil {
		return m.CurrentBlock
	}
	return 0
}

func (m *SyncingInfo) GetHighestBlock() uint64 {
	if m != nil {
		return m.HighestBlock
	}
	return 0
}

func (m *SyncingInfo) GetPulledStates() uint64 {
	if m != nil {
		return m.PulledStates
	}
	return 0
}

func (m *SyncingInfo) GetKnownStates() uint64 {
	if m != nil {
		return m.KnownStates
	}
	return 0
}

// RPCTransaction represents a transaction that will serialize to the RPC representation of a transaction
type RpcTransaction struct {
	BlockHash            string                `protobuf:"bytes,1,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	BlockNumber          uint64                `protobuf:"varint,2,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	From                 string                `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	Gas                  uint64                `protobuf:"varint,4,opt,name=gas,proto3" json:"gas,omitempty"`
	GasPrice             uint64                `protobuf:"varint,5,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	Hash                 string                `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	Input                []byte                `protobuf:"bytes,7,opt,name=input,proto3" json:"input,omitempty"`
	Nonce                uint64                `protobuf:"varint,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	To                   *wrappers.StringValue `protobuf:"bytes,9,opt,name=to,proto3" json:"to,omitempty"`
	TransactionIndex     uint32                `protobuf:"varint,10,opt,name=transactionIndex,proto3" json:"transactionIndex,omitempty"`
	V                    []byte                `protobuf:"bytes,11,opt,name=v,proto3" json:"v,omitempty"`
	R                    []byte                `protobuf:"bytes,12,opt,name=r,proto3" json:"r,omitempty"`
	S                    []byte                `protobuf:"bytes,13,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RpcTransaction) Reset()         { *m = RpcTransaction{} }
func (m *RpcTransaction) String() string { return proto.CompactTextString(m) }
func (*RpcTransaction) ProtoMessage()    {}
func (*RpcTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_413c02bc47c81d3d, []int{19}
}

func (m *RpcTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcTransaction.Unmarshal(m, b)
}
func (m *RpcTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcTransaction.Marshal(b, m, deterministic)
}
func (m *RpcTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcTransaction.Merge(m, src)
}
func (m *RpcTransaction) XXX_Size() int {
	return xxx_messageInfo_RpcTransaction.Size(m)
}
func (m *RpcTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_RpcTransaction proto.InternalMessageInfo

func (m *RpcTransaction) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *RpcTransaction) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *RpcTransaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *RpcTransaction) GetGas() uint64 {
	if m != nil {
		return m.Gas
	}
	return 0
}

func (m *RpcTransaction) GetGasPrice() uint64 {
	if m != nil {
		return m.GasPrice
	}
	return 0
}

func (m *RpcTransaction) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *RpcTransaction) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *RpcTransaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *RpcTransaction) GetTo() *wrappers.StringValue {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *RpcTransaction) GetTransactionIndex() uint32 {
	if m != nil {
		return m.TransactionIndex
	}
	return 0
}

func (m *RpcTransaction) GetV() []byte {
	if m != nil {
		return m.V
	}
	return nil
}

func (m *RpcTransaction) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *RpcTransaction) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

func init() {
	proto.RegisterType((*IsOk)(nil), "common.IsOk")
	proto.RegisterType((*Code)(nil), "common.Code")
	proto.RegisterType((*BlockNumber)(nil), "common.BlockNumber")
	proto.RegisterType((*Address)(nil), "common.Address")
	proto.RegisterType((*Addresses)(nil), "common.Addresses")
	proto.RegisterType((*BlockHash)(nil), "common.BlockHash")
	proto.RegisterType((*Hash)(nil), "common.Hash")
	proto.RegisterType((*Balance)(nil), "common.Balance")
	proto.RegisterType((*GasPrice)(nil), "common.GasPrice")
	proto.RegisterType((*IsFull)(nil), "common.IsFull")
	proto.RegisterType((*Block)(nil), "common.Block")
	proto.RegisterType((*Transaction)(nil), "common.Transaction")
	proto.RegisterType((*Receipt)(nil), "common.Receipt")
	proto.RegisterType((*Log)(nil), "common.Log")
	proto.RegisterType((*DumpAccount)(nil), "common.DumpAccount")
	proto.RegisterMapType((map[string]string)(nil), "common.DumpAccount.StorageEntry")
	proto.RegisterType((*Dump)(nil), "common.Dump")
	proto.RegisterMapType((map[string]*DumpAccount)(nil), "common.Dump.AccountsEntry")
	proto.RegisterType((*BadBlockArgs)(nil), "common.BadBlockArgs")
	proto.RegisterType((*BadBlockArg)(nil), "common.BadBlockArg")
	proto.RegisterType((*SyncingInfo)(nil), "common.SyncingInfo")
	proto.RegisterType((*RpcTransaction)(nil), "common.RpcTransaction")
}

func init() { proto.RegisterFile("v1/common/common.proto", fileDescriptor_413c02bc47c81d3d) }

var fileDescriptor_413c02bc47c81d3d = []byte{
	// 1225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x57, 0x5d, 0x6f, 0xdc, 0x44,
	0x17, 0x96, 0xbd, 0xde, 0xaf, 0xf1, 0x6e, 0xda, 0xfa, 0xad, 0x2a, 0x6b, 0xdf, 0xaa, 0xac, 0x5c,
	0x09, 0xa5, 0xa8, 0xda, 0x88, 0x22, 0x01, 0xea, 0x5d, 0x97, 0x42, 0x89, 0x14, 0xd1, 0xca, 0x01,
	0x84, 0xb8, 0x41, 0xb3, 0xde, 0x89, 0x63, 0xc5, 0xf6, 0x58, 0x33, 0xe3, 0x6d, 0xc2, 0x4f, 0xe1,
	0x8a, 0x0b, 0x7e, 0x13, 0x12, 0xd7, 0x5c, 0xf3, 0x07, 0xb8, 0x42, 0xe7, 0xcc, 0xd8, 0x1e, 0x6f,
	0x36, 0x88, 0xab, 0x9c, 0xe7, 0x9c, 0x67, 0x3d, 0x67, 0xce, 0xe7, 0x84, 0x3c, 0xda, 0x7d, 0x7c,
	0x92, 0xf0, 0xa2, 0xe0, 0xa5, 0xf9, 0xb3, 0xaa, 0x04, 0x57, 0x3c, 0x18, 0x69, 0xb4, 0x78, 0x92,
	0x72, 0x9e, 0xe6, 0xec, 0x04, 0xb5, 0x9b, 0xfa, 0xe2, 0xe4, 0xbd, 0xa0, 0x55, 0xc5, 0x84, 0xd4,
	0xbc, 0x68, 0x41, 0xbc, 0x53, 0xf9, 0xf6, 0x2a, 0x08, 0x88, 0x97, 0xc9, 0xb7, 0x57, 0xa1, 0xb3,
	0x74, 0x8e, 0x27, 0x31, 0xca, 0x60, 0xfb, 0x82, 0x6f, 0x19, 0xd8, 0x12, 0xbe, 0x65, 0x68, 0x9b,
	0xc5, 0x28, 0x47, 0x27, 0xc4, 0x5f, 0xe7, 0x3c, 0xb9, 0xfa, 0xa6, 0x2e, 0x36, 0x4c, 0x04, 0x4b,
	0xe2, 0x6f, 0x3a, 0x88, 0xcc, 0x41, 0x6c, 0xab, 0xa2, 0xa7, 0x64, 0xfc, 0x6a, 0xbb, 0x15, 0x4c,
	0xca, 0x20, 0x24, 0x63, 0xaa, 0x45, 0x24, 0x4e, 0xe3, 0x06, 0x46, 0xcf, 0xc8, 0xd4, 0x90, 0x98,
	0x0c, 0x1e, 0x93, 0x29, 0x6d, 0x40, 0xe8, 0x2c, 0x07, 0xc7, 0xd3, 0xb8, 0x53, 0x00, 0x15, 0x1d,
	0xf8, 0x9a, 0xca, 0x4b, 0xa0, 0x6e, 0x1a, 0x60, 0xbe, 0xd9, 0x29, 0xe0, 0x1e, 0xc8, 0x0a, 0x88,
	0x77, 0xd9, 0x11, 0x50, 0x06, 0xb7, 0xd6, 0x34, 0xa7, 0x65, 0xc2, 0xc0, 0xad, 0x8d, 0x16, 0x1b,
	0xb7, 0x0c, 0x8c, 0x3e, 0x24, 0x93, 0x37, 0x54, 0xbe, 0x13, 0x59, 0xc2, 0x82, 0x05, 0x99, 0xa4,
	0x46, 0x36, 0xd7, 0x6c, 0x71, 0xb4, 0x24, 0xa3, 0x53, 0xf9, 0x55, 0x9d, 0xe7, 0xc1, 0x23, 0x32,
	0xca, 0x50, 0x32, 0x01, 0x35, 0x28, 0xfa, 0xc5, 0x23, 0x43, 0x74, 0x1b, 0x18, 0x65, 0x17, 0x2c,
	0x2f, 0x36, 0xa8, 0x75, 0xd2, 0xed, 0x9c, 0x0c, 0x9e, 0x10, 0x52, 0x51, 0xc1, 0x4a, 0x85, 0xf7,
	0x1b, 0xa0, 0xc5, 0xd2, 0x04, 0x0f, 0xc9, 0xb0, 0xe4, 0xe0, 0xb7, 0x87, 0x9f, 0xd2, 0x00, 0xee,
	0x53, 0x64, 0xd7, 0xf8, 0x93, 0xa1, 0xbe, 0x8f, 0x81, 0x10, 0xae, 0x9c, 0xa7, 0x72, 0x9d, 0x73,
	0x5e, 0x84, 0x23, 0xcc, 0x6a, 0xa7, 0x00, 0xab, 0x54, 0x54, 0xb1, 0x98, 0x73, 0x15, 0x8e, 0x75,
	0x30, 0x5b, 0x05, 0x9c, 0x55, 0x64, 0x25, 0x13, 0xe1, 0x04, 0x2d, 0x1a, 0x80, 0x87, 0xdb, 0xec,
	0xe2, 0x22, 0x4b, 0xea, 0x5c, 0xdd, 0x84, 0x53, 0x74, 0xc3, 0xd2, 0xc0, 0x37, 0xd9, 0xb5, 0x12,
	0xf4, 0x35, 0x55, 0x34, 0x24, 0xfa, 0xc4, 0x56, 0x01, 0x77, 0x96, 0xd9, 0xcf, 0x2c, 0xf4, 0xf1,
	0x77, 0x28, 0x9b, 0x38, 0x9f, 0x65, 0x45, 0xa6, 0xc2, 0x19, 0xea, 0x5b, 0x0c, 0x37, 0x4b, 0xa9,
	0xfc, 0x4e, 0xb2, 0x6d, 0x38, 0x47, 0x53, 0x03, 0xe1, 0x1c, 0x95, 0x15, 0x4c, 0x2a, 0x5a, 0x54,
	0xe1, 0x91, 0xf6, 0xbd, 0x55, 0x04, 0x1f, 0x91, 0xfb, 0x4a, 0xd0, 0x52, 0xd2, 0x44, 0x65, 0xbc,
	0x94, 0x78, 0xc1, 0x7b, 0x48, 0xba, 0xa5, 0x0f, 0x22, 0x32, 0x13, 0x2c, 0x61, 0x59, 0xa5, 0x34,
	0xef, 0x3e, 0xf2, 0x7a, 0x3a, 0x88, 0x05, 0x13, 0x82, 0x8b, 0xf0, 0x81, 0x8e, 0x05, 0x82, 0xe0,
	0x33, 0x32, 0xb3, 0xbf, 0x16, 0x06, 0xcb, 0xc1, 0xb1, 0xff, 0xe2, 0x7f, 0x2b, 0xd3, 0x9f, 0xdf,
	0x76, 0xb6, 0xb8, 0x47, 0x8c, 0xfe, 0x74, 0x89, 0x6f, 0x59, 0xa1, 0x44, 0xd4, 0xb5, 0x55, 0xd2,
	0x06, 0xf5, 0xab, 0xdd, 0xdd, 0xab, 0x76, 0x08, 0xe6, 0x85, 0xe0, 0x85, 0x29, 0x13, 0x94, 0x83,
	0x23, 0xe2, 0x2a, 0x8e, 0xd5, 0x31, 0x8d, 0x5d, 0xc5, 0xdb, 0x22, 0x1b, 0x5a, 0x45, 0xf6, 0x90,
	0x0c, 0x77, 0x34, 0xaf, 0x19, 0x16, 0xc4, 0x34, 0xd6, 0x20, 0x98, 0x11, 0x67, 0x67, 0x8a, 0xc0,
	0xd9, 0x01, 0x6a, 0x12, 0xef, 0x08, 0x40, 0x12, 0x73, 0x3d, 0x8d, 0x1d, 0xb9, 0x17, 0xdc, 0xd3,
	0x72, 0xcb, 0xae, 0x31, 0xd3, 0x5e, 0x7c, 0x4b, 0xdf, 0x15, 0xac, 0x6f, 0x17, 0xec, 0xde, 0x10,
	0xd1, 0x59, 0xb7, 0x55, 0xc1, 0x7d, 0x32, 0x48, 0xa9, 0x34, 0x49, 0x07, 0xb1, 0xd7, 0x8e, 0x47,
	0x6d, 0x99, 0xe8, 0x56, 0x7d, 0x48, 0x86, 0x59, 0x59, 0xd5, 0x3a, 0xc7, 0xb3, 0x58, 0x83, 0xe8,
	0xd7, 0x01, 0x19, 0xc7, 0x3a, 0x8b, 0x87, 0xc6, 0xd6, 0xde, 0x89, 0x56, 0xa9, 0xb9, 0xfd, 0x52,
	0x7b, 0x4e, 0x1e, 0x24, 0x75, 0x51, 0xe7, 0x54, 0x65, 0x3b, 0xf6, 0xc6, 0x70, 0x06, 0xc8, 0xb9,
	0x6d, 0x38, 0x18, 0x1d, 0xef, 0x8e, 0xe8, 0xf4, 0xf2, 0x3b, 0xdc, 0xcf, 0xef, 0x31, 0xb9, 0x67,
	0xfd, 0x02, 0x39, 0x3a, 0x63, 0xfb, 0xea, 0xb6, 0x12, 0xc6, 0xb7, 0x2a, 0x61, 0xd2, 0x56, 0xc2,
	0x31, 0xb9, 0x97, 0xf0, 0x52, 0x09, 0x9a, 0x28, 0x33, 0x79, 0x4d, 0x46, 0xf7, 0xd5, 0x50, 0x8d,
	0x30, 0x05, 0x6a, 0x69, 0xb2, 0x6a, 0x10, 0x9c, 0x22, 0xa0, 0x41, 0x7c, 0xbd, 0x1d, 0x40, 0xee,
	0x0f, 0x98, 0xd9, 0xfe, 0x80, 0xf9, 0x80, 0x78, 0x00, 0xc2, 0x39, 0x36, 0x86, 0xdf, 0x34, 0xc6,
	0x19, 0x4f, 0x63, 0x34, 0x44, 0x7f, 0x39, 0x64, 0x70, 0xc6, 0x53, 0x08, 0xbe, 0x60, 0x05, 0xdf,
	0xb1, 0xad, 0x19, 0xa3, 0x0d, 0xdc, 0x4f, 0x9c, 0x7b, 0x30, 0x71, 0xea, 0x5a, 0xc7, 0x59, 0x27,
	0xa5, 0x81, 0xfd, 0xf0, 0x7a, 0xfb, 0xe1, 0xc5, 0xa2, 0x81, 0x5f, 0x41, 0xe0, 0xe7, 0xb1, 0x06,
	0xf6, 0xca, 0x1a, 0xf5, 0x56, 0x96, 0xd5, 0xa4, 0xe3, 0x5e, 0x93, 0x06, 0xc4, 0xdb, 0xc2, 0xb0,
	0x9b, 0xe8, 0xb0, 0x80, 0x8c, 0x5c, 0x5e, 0x65, 0x09, 0xc4, 0x78, 0x80, 0x5c, 0x44, 0xd1, 0xdf,
	0x0e, 0xf1, 0x5f, 0xd7, 0x45, 0xf5, 0x2a, 0x49, 0x78, 0x5d, 0xaa, 0xbb, 0x37, 0x51, 0xd7, 0x38,
	0xae, 0xdd, 0x38, 0x4d, 0x0a, 0x4c, 0xcb, 0x63, 0x0a, 0xfe, 0x4f, 0xa6, 0xb0, 0xa8, 0x7f, 0xba,
	0xec, 0x6e, 0x39, 0x01, 0x45, 0xe3, 0x1c, 0x6e, 0x74, 0xd3, 0xff, 0x20, 0x07, 0x2f, 0xc9, 0x58,
	0x2a, 0x2e, 0x68, 0x0a, 0x13, 0x00, 0x12, 0xb3, 0x6c, 0x12, 0x63, 0xb9, 0xb6, 0x3a, 0xd7, 0x94,
	0x2f, 0x4b, 0x25, 0x6e, 0xe2, 0xe6, 0x07, 0x8b, 0x97, 0x64, 0x66, 0x1b, 0xa0, 0x4f, 0xaf, 0xd8,
	0x8d, 0x71, 0x1e, 0xc4, 0x6e, 0xba, 0xb8, 0xd6, 0x74, 0x79, 0xe9, 0x7e, 0xee, 0x44, 0xbf, 0x39,
	0xc4, 0x83, 0x13, 0xda, 0x5b, 0x38, 0xd6, 0x2d, 0x3e, 0x25, 0x13, 0xaa, 0x4f, 0x96, 0xa1, 0x8b,
	0x5e, 0x2d, 0x6c, 0xaf, 0x56, 0xc6, 0x2d, 0xa9, 0xfd, 0x69, 0xb9, 0x8b, 0x77, 0x64, 0xde, 0x33,
	0x1d, 0xf0, 0xe8, 0x99, 0xed, 0x91, 0x35, 0x9f, 0xad, 0xdb, 0xda, 0x6e, 0xbe, 0x21, 0xb3, 0x35,
	0xdd, 0xe2, 0xee, 0x7e, 0x25, 0x52, 0x09, 0x53, 0x7e, 0x63, 0x61, 0x7c, 0xa0, 0x58, 0x5f, 0xb1,
	0xb8, 0x71, 0x8f, 0x18, 0xfd, 0x40, 0x7c, 0xcb, 0x78, 0xe8, 0x51, 0x02, 0xce, 0x8a, 0xbc, 0x32,
	0xa1, 0x02, 0x31, 0x78, 0x4a, 0x86, 0x58, 0xa2, 0x98, 0x62, 0xff, 0xc5, 0xbc, 0x3d, 0x06, 0x94,
	0xb1, 0xb6, 0x45, 0x7f, 0x38, 0xc4, 0x3f, 0xbf, 0x29, 0x93, 0xac, 0x4c, 0x4f, 0xcb, 0x0b, 0x0e,
	0x85, 0x9e, 0x49, 0xa3, 0x30, 0x0d, 0xd4, 0x29, 0x60, 0x65, 0x4b, 0x45, 0x85, 0xc2, 0x4f, 0x98,
	0x7a, 0xb2, 0x34, 0xb0, 0x00, 0x93, 0x5a, 0xc0, 0x1b, 0x63, 0xdd, 0x9e, 0xec, 0xc5, 0x3d, 0x1d,
	0x70, 0x2e, 0xb3, 0xf4, 0x92, 0x49, 0xc3, 0xd1, 0x13, 0xad, 0xa7, 0x03, 0x4e, 0x55, 0xe7, 0x39,
	0xdb, 0x9e, 0xc3, 0x1b, 0x42, 0x62, 0xcd, 0x79, 0x71, 0x4f, 0x07, 0xed, 0x7c, 0x55, 0xf2, 0xf7,
	0xa5, 0xa1, 0x8c, 0x74, 0x3b, 0x5b, 0xaa, 0xe8, 0x77, 0x97, 0x1c, 0xc5, 0x55, 0x62, 0xaf, 0xc7,
	0x7f, 0x7d, 0xf4, 0xfd, 0x87, 0x09, 0x71, 0x68, 0x51, 0x9a, 0x05, 0xe3, 0x1d, 0x5e, 0x30, 0xc3,
	0xbd, 0x05, 0xd3, 0xe4, 0x6e, 0xd4, 0x5f, 0xa3, 0x7a, 0xe9, 0x8c, 0xad, 0xa5, 0xd3, 0xf5, 0xed,
	0xc4, 0xee, 0xdb, 0xe7, 0x38, 0x8c, 0xa7, 0x98, 0xd2, 0xc7, 0x2b, 0xfd, 0x52, 0x5f, 0x35, 0x2f,
	0xf5, 0xd5, 0xb9, 0x12, 0x59, 0x99, 0x7e, 0x0f, 0x15, 0x88, 0xa3, 0xfa, 0xae, 0x05, 0x3b, 0x3f,
	0xb0, 0x42, 0x70, 0x6d, 0xeb, 0x89, 0xdc, 0xac, 0x6d, 0x3d, 0x86, 0x9b, 0xb5, 0x3d, 0xd7, 0x48,
	0xae, 0x27, 0x3f, 0x9a, 0x7f, 0x15, 0x36, 0x23, 0x3c, 0xf9, 0x93, 0x7f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x41, 0x22, 0x21, 0x2d, 0x53, 0x0c, 0x00, 0x00,
}
