version: '3'
services:
  docs:
    build: .
    image: cpchain:docs
    container_name: sphinx-docs
    user: "${UID}:${GID}"
    volumes:
         - ..:/docs
  serve:
    build: .
    image: cpchain:docs
    container_name: docs-serve
    user: "${UID}:${GID}"
    volumes:
      - ..:/docs
    ports:
      - "9528:9528"
