#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE[0]}")"

./init

./start bootnodes
./start validators
./start proposers
./start ca

sleep 5

./deploy-contracts

./stop ca
./start civilians

tail -f logs/p1.log
