#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE[0]}")"

target=$1

if [ $target ]; then
    case $target in
    bootnodes)
        pkill -f "datadir/b1"
        ;;
    all)
        pkill -f cpchain
        pkill -f "cpchain run"
        ;;
    *)
        pkill -f "datadir/$target"
    esac
fi
