// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/cpc/cpc.proto

package cpc

import (
	fmt "fmt"
	math "math"

	common "bitbucket.org/cpchain/chain/api/grpc/v1/common"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//ChainReaderRequest ChainReader request arguments
type ChainReaderRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	BlockHash            string   `protobuf:"bytes,2,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	BlockNumber          int64    `protobuf:"varint,3,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	IsFull               bool     `protobuf:"varint,4,opt,name=isFull,proto3" json:"isFull,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainReaderRequest) Reset()         { *m = ChainReaderRequest{} }
func (m *ChainReaderRequest) String() string { return proto.CompactTextString(m) }
func (*ChainReaderRequest) ProtoMessage()    {}
func (*ChainReaderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dce01fedbe4c8ea, []int{0}
}

func (m *ChainReaderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainReaderRequest.Unmarshal(m, b)
}
func (m *ChainReaderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainReaderRequest.Marshal(b, m, deterministic)
}
func (m *ChainReaderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainReaderRequest.Merge(m, src)
}
func (m *ChainReaderRequest) XXX_Size() int {
	return xxx_messageInfo_ChainReaderRequest.Size(m)
}
func (m *ChainReaderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainReaderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChainReaderRequest proto.InternalMessageInfo

func (m *ChainReaderRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ChainReaderRequest) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *ChainReaderRequest) GetBlockNumber() int64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *ChainReaderRequest) GetIsFull() bool {
	if m != nil {
		return m.IsFull
	}
	return false
}

//TransactionCount transaction count
type TransactionCount struct {
	TransactionCount     uint64   `protobuf:"varint,1,opt,name=transactionCount,proto3" json:"transactionCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionCount) Reset()         { *m = TransactionCount{} }
func (m *TransactionCount) String() string { return proto.CompactTextString(m) }
func (*TransactionCount) ProtoMessage()    {}
func (*TransactionCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dce01fedbe4c8ea, []int{1}
}

func (m *TransactionCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionCount.Unmarshal(m, b)
}
func (m *TransactionCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionCount.Marshal(b, m, deterministic)
}
func (m *TransactionCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionCount.Merge(m, src)
}
func (m *TransactionCount) XXX_Size() int {
	return xxx_messageInfo_TransactionCount.Size(m)
}
func (m *TransactionCount) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionCount.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionCount proto.InternalMessageInfo

func (m *TransactionCount) GetTransactionCount() uint64 {
	if m != nil {
		return m.TransactionCount
	}
	return 0
}

//TransactionPoolReaderRequest request parameters
type TransactionPoolReaderRequest struct {
	BlockNumber          uint64   `protobuf:"varint,1,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	Index                uint64   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	BlockHash            string   `protobuf:"bytes,3,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionPoolReaderRequest) Reset()         { *m = TransactionPoolReaderRequest{} }
func (m *TransactionPoolReaderRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionPoolReaderRequest) ProtoMessage()    {}
func (*TransactionPoolReaderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dce01fedbe4c8ea, []int{2}
}

func (m *TransactionPoolReaderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionPoolReaderRequest.Unmarshal(m, b)
}
func (m *TransactionPoolReaderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionPoolReaderRequest.Marshal(b, m, deterministic)
}
func (m *TransactionPoolReaderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionPoolReaderRequest.Merge(m, src)
}
func (m *TransactionPoolReaderRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionPoolReaderRequest.Size(m)
}
func (m *TransactionPoolReaderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionPoolReaderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionPoolReaderRequest proto.InternalMessageInfo

func (m *TransactionPoolReaderRequest) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *TransactionPoolReaderRequest) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *TransactionPoolReaderRequest) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *TransactionPoolReaderRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

//RawTransaction transaction bytes
type RawTransaction struct {
	RawTransaction       []byte   `protobuf:"bytes,1,opt,name=rawTransaction,proto3" json:"rawTransaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawTransaction) Reset()         { *m = RawTransaction{} }
func (m *RawTransaction) String() string { return proto.CompactTextString(m) }
func (*RawTransaction) ProtoMessage()    {}
func (*RawTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dce01fedbe4c8ea, []int{3}
}

func (m *RawTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawTransaction.Unmarshal(m, b)
}
func (m *RawTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawTransaction.Marshal(b, m, deterministic)
}
func (m *RawTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawTransaction.Merge(m, src)
}
func (m *RawTransaction) XXX_Size() int {
	return xxx_messageInfo_RawTransaction.Size(m)
}
func (m *RawTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_RawTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_RawTransaction proto.InternalMessageInfo

func (m *RawTransaction) GetRawTransaction() []byte {
	if m != nil {
		return m.RawTransaction
	}
	return nil
}

//TransactionHash transaction hash
type TransactionHash struct {
	TransactionHash      string   `protobuf:"bytes,1,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionHash) Reset()         { *m = TransactionHash{} }
func (m *TransactionHash) String() string { return proto.CompactTextString(m) }
func (*TransactionHash) ProtoMessage()    {}
func (*TransactionHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dce01fedbe4c8ea, []int{4}
}

func (m *TransactionHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionHash.Unmarshal(m, b)
}
func (m *TransactionHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionHash.Marshal(b, m, deterministic)
}
func (m *TransactionHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionHash.Merge(m, src)
}
func (m *TransactionHash) XXX_Size() int {
	return xxx_messageInfo_TransactionHash.Size(m)
}
func (m *TransactionHash) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionHash.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionHash proto.InternalMessageInfo

func (m *TransactionHash) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func init() {
	proto.RegisterType((*ChainReaderRequest)(nil), "cpc.ChainReaderRequest")
	proto.RegisterType((*TransactionCount)(nil), "cpc.TransactionCount")
	proto.RegisterType((*TransactionPoolReaderRequest)(nil), "cpc.TransactionPoolReaderRequest")
	proto.RegisterType((*RawTransaction)(nil), "cpc.RawTransaction")
	proto.RegisterType((*TransactionHash)(nil), "cpc.TransactionHash")
}

func init() { proto.RegisterFile("v1/cpc/cpc.proto", fileDescriptor_2dce01fedbe4c8ea) }

var fileDescriptor_2dce01fedbe4c8ea = []byte{
	// 944 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0x41, 0x6f, 0x1b, 0x45,
	0x14, 0xc7, 0xb5, 0x71, 0x9a, 0xb8, 0x2f, 0x4d, 0xe2, 0x8e, 0x93, 0xd4, 0x75, 0x4c, 0x62, 0x0f,
	0x6d, 0x88, 0x4c, 0xb1, 0x55, 0x17, 0xd4, 0x2a, 0x08, 0xa4, 0x38, 0x02, 0x93, 0x43, 0x20, 0xda,
	0xb6, 0x91, 0x40, 0x48, 0x30, 0x1e, 0x4f, 0xdd, 0x55, 0xd7, 0x33, 0xdb, 0xdd, 0x31, 0x25, 0xe2,
	0x04, 0x07, 0xb8, 0x71, 0xe1, 0xc2, 0x01, 0x89, 0xef, 0xc0, 0x57, 0xe1, 0x03, 0x70, 0xe9, 0x07,
	0x41, 0xf3, 0x3c, 0xdb, 0xec, 0x6e, 0x76, 0x93, 0x08, 0x71, 0x88, 0xe2, 0x79, 0x33, 0xfe, 0xff,
	0x7f, 0xef, 0xcd, 0x9b, 0x19, 0x43, 0xe5, 0xbb, 0xfb, 0x5d, 0x1e, 0x70, 0xf3, 0xd7, 0x09, 0x42,
	0xa5, 0x15, 0x29, 0xf1, 0x80, 0xd7, 0xab, 0x5c, 0x4d, 0x26, 0x4a, 0x76, 0x67, 0xff, 0x66, 0x33,
	0xf5, 0xcd, 0xb1, 0x52, 0x63, 0x5f, 0x74, 0x71, 0x34, 0x9c, 0x3e, 0xeb, 0x8a, 0x49, 0xa0, 0x4f,
	0xed, 0xe4, 0x56, 0x76, 0xf2, 0x55, 0xc8, 0x82, 0x40, 0x84, 0x91, 0x9d, 0x6f, 0xd8, 0x79, 0x16,
	0x78, 0x5d, 0x26, 0xa5, 0xd2, 0x4c, 0x7b, 0x4a, 0xda, 0x59, 0xfa, 0xb3, 0x03, 0xe4, 0xe0, 0x39,
	0xf3, 0xa4, 0x2b, 0xd8, 0x48, 0x84, 0xae, 0x78, 0x39, 0x15, 0x91, 0x26, 0x35, 0x58, 0x64, 0xa3,
	0x51, 0x28, 0xa2, 0xa8, 0xe6, 0x34, 0x9d, 0xdd, 0xeb, 0x6e, 0x3c, 0x24, 0x0d, 0xb8, 0x3e, 0xf4,
	0x15, 0x7f, 0xf1, 0x19, 0x8b, 0x9e, 0xd7, 0xe6, 0x70, 0xee, 0x2c, 0x40, 0x9a, 0xb0, 0x84, 0x83,
	0xcf, 0xa7, 0x93, 0xa1, 0x08, 0x6b, 0xa5, 0xa6, 0xb3, 0x5b, 0x72, 0x93, 0x21, 0xb2, 0x01, 0x0b,
	0x5e, 0xf4, 0xe9, 0xd4, 0xf7, 0x6b, 0xf3, 0x4d, 0x67, 0xb7, 0xec, 0xda, 0x11, 0xfd, 0x18, 0x2a,
	0x4f, 0x42, 0x26, 0x23, 0xc6, 0x0d, 0xde, 0x81, 0x9a, 0x4a, 0x4d, 0xda, 0x50, 0xd1, 0x99, 0x18,
	0xe2, 0xcc, 0xbb, 0xe7, 0xe2, 0xf4, 0x57, 0x07, 0x1a, 0x09, 0x81, 0x63, 0xa5, 0xfc, 0x74, 0x4a,
	0x19, 0xb4, 0x99, 0x4e, 0x0a, 0x6d, 0x0d, 0xae, 0x79, 0x72, 0x24, 0xbe, 0xc7, 0xb4, 0xe6, 0xdd,
	0xd9, 0x20, 0x9d, 0x70, 0x29, 0x9b, 0x70, 0xa2, 0x50, 0xf3, 0xa9, 0x42, 0xd1, 0x47, 0xb0, 0xe2,
	0xb2, 0x57, 0x09, 0x24, 0xb2, 0x03, 0x2b, 0x61, 0x2a, 0x82, 0x10, 0x37, 0xdc, 0x4c, 0x94, 0x7e,
	0x08, 0xab, 0x89, 0x21, 0xda, 0xec, 0xc2, 0xaa, 0x4e, 0x87, 0xec, 0xbe, 0x64, 0xc3, 0xbd, 0x6f,
	0xa1, 0x7c, 0xa0, 0x3c, 0x39, 0x64, 0x91, 0x20, 0x4f, 0x12, 0x9f, 0x37, 0x3a, 0xb3, 0x3e, 0xe8,
	0xc4, 0x7d, 0xd2, 0xf9, 0xc4, 0x34, 0x51, 0x7d, 0xb5, 0x63, 0x5b, 0x6d, 0xdf, 0x72, 0x6f, 0xff,
	0xf4, 0xf7, 0xeb, 0xdf, 0xe6, 0x6e, 0xd3, 0x35, 0xec, 0x98, 0xb8, 0x4b, 0xad, 0xcc, 0x9e, 0xd3,
	0xee, 0x7d, 0x0d, 0x4b, 0x47, 0x9e, 0x34, 0x85, 0x35, 0xe5, 0x25, 0x47, 0xb0, 0x70, 0xe4, 0x49,
	0x4f, 0x8e, 0x0b, 0x2d, 0x6e, 0xc4, 0x16, 0x87, 0xd1, 0x17, 0x2f, 0xe8, 0x5b, 0xa8, 0x7f, 0x8b,
	0x92, 0xa4, 0xfe, 0x04, 0x15, 0x8c, 0xfa, 0x18, 0x96, 0xf7, 0x39, 0x37, 0x5b, 0x6a, 0xf5, 0x4f,
	0xa0, 0x6c, 0x03, 0x51, 0xa1, 0xc3, 0xcd, 0x4c, 0x12, 0xa2, 0x20, 0x0d, 0x66, 0x85, 0x8c, 0xd1,
	0x5f, 0x73, 0x50, 0xc1, 0xce, 0x7f, 0xac, 0x99, 0x16, 0xd6, 0xec, 0x29, 0x94, 0x07, 0x2c, 0x3a,
	0x0e, 0x3d, 0x5e, 0x5c, 0xb1, 0x4a, 0x6c, 0x16, 0xaf, 0xcc, 0xf7, 0x1a, 0xdb, 0xd9, 0x3d, 0xa7,
	0x4d, 0x14, 0xac, 0x1e, 0x1b, 0x11, 0xae, 0xfc, 0x13, 0x11, 0x46, 0xa6, 0x19, 0x8a, 0xd4, 0x1b,
	0xe7, 0xe2, 0x4f, 0x0f, 0xa5, 0x7e, 0xd0, 0x3b, 0x61, 0xfe, 0x54, 0xd0, 0x1d, 0x74, 0x6a, 0xd2,
	0xcd, 0xa4, 0x53, 0x90, 0x96, 0x36, 0x86, 0x27, 0xb0, 0xf8, 0xf8, 0x54, 0xf2, 0x8b, 0x76, 0xa5,
	0x1a, 0xa7, 0x61, 0x17, 0x1e, 0xca, 0x67, 0x8a, 0x6e, 0xa1, 0x7e, 0x8d, 0x56, 0x93, 0xfa, 0xd1,
	0x6c, 0x81, 0x29, 0xda, 0xeb, 0x12, 0x2c, 0x25, 0xae, 0x0b, 0x32, 0x84, 0xe5, 0x81, 0xd0, 0x7d,
	0x73, 0x1c, 0x66, 0x47, 0xf6, 0x52, 0xb7, 0xfe, 0xd9, 0x81, 0xa3, 0x77, 0xd0, 0x6d, 0x8b, 0xde,
	0x4e, 0xd5, 0x2d, 0xa9, 0x67, 0x72, 0xf9, 0x12, 0xc0, 0x78, 0x30, 0x9f, 0x49, 0x2e, 0xc8, 0xad,
	0x8e, 0xb9, 0x31, 0xcf, 0x5f, 0x59, 0x67, 0x8d, 0x6c, 0x57, 0xd2, 0x16, 0xaa, 0x6f, 0xd2, 0x8d,
	0xac, 0xfa, 0x6c, 0xde, 0x48, 0x73, 0xa8, 0xc4, 0xf8, 0xfd, 0x53, 0x7b, 0x0b, 0x14, 0x1a, 0x2c,
	0xa7, 0x52, 0xa0, 0xef, 0xa0, 0x7c, 0x8b, 0x36, 0xf2, 0xe0, 0x63, 0x35, 0x63, 0xf2, 0x0d, 0xac,
	0x9c, 0x99, 0xe0, 0x69, 0xbe, 0xaa, 0xc5, 0x5d, 0xb4, 0xd8, 0xa6, 0xf5, 0x7c, 0x0b, 0xa3, 0x65,
	0x0c, 0x8e, 0x61, 0x71, 0x20, 0xf4, 0x81, 0x1a, 0x5d, 0x50, 0x9d, 0x37, 0x67, 0xd0, 0x2c, 0xcb,
	0xdf, 0xe6, 0xb1, 0xd0, 0x5c, 0x8d, 0xf0, 0x88, 0xff, 0x53, 0x86, 0xf5, 0xdc, 0xcb, 0x94, 0xfc,
	0xe2, 0x40, 0x73, 0x20, 0x74, 0xf6, 0xaa, 0xee, 0x9f, 0x26, 0xf6, 0x95, 0xe4, 0x6d, 0x76, 0x7d,
	0x1d, 0xd1, 0xb2, 0x5f, 0xa4, 0x0f, 0x11, 0xe5, 0x3e, 0xbd, 0x97, 0x41, 0xb9, 0xd0, 0xc1, 0x64,
	0xfd, 0xa3, 0x03, 0x5b, 0xc5, 0x24, 0x58, 0xe7, 0x9b, 0x29, 0x0e, 0x13, 0x2a, 0xa2, 0xf8, 0x00,
	0x29, 0xba, 0xb4, 0x7d, 0x35, 0x8a, 0xb8, 0xf2, 0x7f, 0x38, 0xf0, 0x76, 0x9a, 0x21, 0x85, 0xb9,
	0x2f, 0x47, 0x87, 0xf8, 0x86, 0xb4, 0xb2, 0xae, 0xe7, 0x9e, 0xa7, 0xfa, 0x46, 0xcc, 0xea, 0x06,
	0x3c, 0xf9, 0x18, 0xec, 0x21, 0xd9, 0xfb, 0xb4, 0x5b, 0x4c, 0x96, 0xeb, 0x69, 0xf0, 0x7e, 0x77,
	0xa0, 0x95, 0x8b, 0x67, 0xf8, 0xff, 0x0f, 0xb8, 0x47, 0x08, 0xd7, 0xa3, 0xef, 0x5d, 0x0a, 0x97,
	0x74, 0x34, 0x68, 0x7f, 0x3a, 0xb0, 0x33, 0x10, 0x3a, 0xfd, 0x42, 0xfe, 0xe7, 0xe2, 0x55, 0x71,
	0x49, 0x5a, 0x8c, 0x7e, 0x84, 0x70, 0x0f, 0x69, 0x2f, 0x03, 0x77, 0x05, 0x4f, 0x43, 0xf8, 0x12,
	0xd6, 0xb2, 0xb5, 0xc3, 0xa6, 0x5a, 0xcb, 0xe2, 0x60, 0x5f, 0x15, 0x55, 0xe8, 0x5d, 0x84, 0xb8,
	0x4b, 0x9b, 0x17, 0x55, 0x28, 0x6e, 0x27, 0x1f, 0xd6, 0xd3, 0x96, 0xae, 0xe0, 0xc2, 0x0b, 0x74,
	0x81, 0xe7, 0x9b, 0x1b, 0xcf, 0x2e, 0xa3, 0xf7, 0xd0, 0x6c, 0x87, 0xb6, 0x8a, 0xcd, 0xec, 0x52,
	0xe3, 0xf6, 0x03, 0x54, 0x73, 0xce, 0xcf, 0x55, 0xca, 0x5d, 0x70, 0x88, 0xda, 0x68, 0x7f, 0x87,
	0x6e, 0x5f, 0x72, 0x88, 0xf6, 0x9c, 0x76, 0xff, 0xda, 0x57, 0xe6, 0xe7, 0xee, 0x70, 0x01, 0x9f,
	0x89, 0x07, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x91, 0xce, 0x4c, 0x8e, 0x0e, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CoinbaseClient is the client API for Coinbase service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CoinbaseClient interface {
	// Coinbase is the address that mining rewards will be send to
	Coinbase(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*common.Address, error)
}

type coinbaseClient struct {
	cc *grpc.ClientConn
}

func NewCoinbaseClient(cc *grpc.ClientConn) CoinbaseClient {
	return &coinbaseClient{cc}
}

func (c *coinbaseClient) Coinbase(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*common.Address, error) {
	out := new(common.Address)
	err := c.cc.Invoke(ctx, "/cpc.Coinbase/Coinbase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoinbaseServer is the server API for Coinbase service.
type CoinbaseServer interface {
	// Coinbase is the address that mining rewards will be send to
	Coinbase(context.Context, *empty.Empty) (*common.Address, error)
}

func RegisterCoinbaseServer(s *grpc.Server, srv CoinbaseServer) {
	s.RegisterService(&_Coinbase_serviceDesc, srv)
}

func _Coinbase_Coinbase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinbaseServer).Coinbase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cpc.Coinbase/Coinbase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinbaseServer).Coinbase(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Coinbase_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cpc.Coinbase",
	HandlerType: (*CoinbaseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Coinbase",
			Handler:    _Coinbase_Coinbase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/cpc/cpc.proto",
}

// MinerReaderClient is the client API for MinerReader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MinerReaderClient interface {
	// Mining returns an indication if this node is currently mining.
	Mining(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*common.IsOk, error)
}

type minerReaderClient struct {
	cc *grpc.ClientConn
}

func NewMinerReaderClient(cc *grpc.ClientConn) MinerReaderClient {
	return &minerReaderClient{cc}
}

func (c *minerReaderClient) Mining(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*common.IsOk, error) {
	out := new(common.IsOk)
	err := c.cc.Invoke(ctx, "/cpc.MinerReader/Mining", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MinerReaderServer is the server API for MinerReader service.
type MinerReaderServer interface {
	// Mining returns an indication if this node is currently mining.
	Mining(context.Context, *empty.Empty) (*common.IsOk, error)
}

func RegisterMinerReaderServer(s *grpc.Server, srv MinerReaderServer) {
	s.RegisterService(&_MinerReader_serviceDesc, srv)
}

func _MinerReader_Mining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinerReaderServer).Mining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cpc.MinerReader/Mining",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinerReaderServer).Mining(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _MinerReader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cpc.MinerReader",
	HandlerType: (*MinerReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Mining",
			Handler:    _MinerReader_Mining_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/cpc/cpc.proto",
}

// AccountReaderClient is the client API for AccountReader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountReaderClient interface {
	// Accounts returns the collection of accounts this node manages
	Accounts(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*common.Addresses, error)
}

type accountReaderClient struct {
	cc *grpc.ClientConn
}

func NewAccountReaderClient(cc *grpc.ClientConn) AccountReaderClient {
	return &accountReaderClient{cc}
}

func (c *accountReaderClient) Accounts(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*common.Addresses, error) {
	out := new(common.Addresses)
	err := c.cc.Invoke(ctx, "/cpc.AccountReader/Accounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountReaderServer is the server API for AccountReader service.
type AccountReaderServer interface {
	// Accounts returns the collection of accounts this node manages
	Accounts(context.Context, *empty.Empty) (*common.Addresses, error)
}

func RegisterAccountReaderServer(s *grpc.Server, srv AccountReaderServer) {
	s.RegisterService(&_AccountReader_serviceDesc, srv)
}

func _AccountReader_Accounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountReaderServer).Accounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cpc.AccountReader/Accounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountReaderServer).Accounts(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountReader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cpc.AccountReader",
	HandlerType: (*AccountReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Accounts",
			Handler:    _AccountReader_Accounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/cpc/cpc.proto",
}

// ChainStateReaderClient is the client API for ChainStateReader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChainStateReaderClient interface {
	// GasPrice returns a suggestion for a gas price.
	GasPrice(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*common.GasPrice, error)
	// ProtocolVersion returns the current Cpchain protocol version this node supports
	ProtocolVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*wrappers.UInt32Value, error)
	// Syncing returns false in case the node is currently not syncing with the network. It can be up to date or has not
	// yet received the latest block headers from its pears. In case it is synchronizing:
	// - startingBlock: block number this node started to synchronise from
	// - currentBlock:  block number this node is currently importing
	// - highestBlock:  block number of the highest block header this node has received from peers
	// - pulledStates:  number of state entries processed until now
	// - knownStates:   number of known state entries that still need to be pulled
	Syncing(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*common.SyncingInfo, error)
}

type chainStateReaderClient struct {
	cc *grpc.ClientConn
}

func NewChainStateReaderClient(cc *grpc.ClientConn) ChainStateReaderClient {
	return &chainStateReaderClient{cc}
}

func (c *chainStateReaderClient) GasPrice(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*common.GasPrice, error) {
	out := new(common.GasPrice)
	err := c.cc.Invoke(ctx, "/cpc.ChainStateReader/GasPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainStateReaderClient) ProtocolVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*wrappers.UInt32Value, error) {
	out := new(wrappers.UInt32Value)
	err := c.cc.Invoke(ctx, "/cpc.ChainStateReader/ProtocolVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainStateReaderClient) Syncing(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*common.SyncingInfo, error) {
	out := new(common.SyncingInfo)
	err := c.cc.Invoke(ctx, "/cpc.ChainStateReader/Syncing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChainStateReaderServer is the server API for ChainStateReader service.
type ChainStateReaderServer interface {
	// GasPrice returns a suggestion for a gas price.
	GasPrice(context.Context, *empty.Empty) (*common.GasPrice, error)
	// ProtocolVersion returns the current Cpchain protocol version this node supports
	ProtocolVersion(context.Context, *empty.Empty) (*wrappers.UInt32Value, error)
	// Syncing returns false in case the node is currently not syncing with the network. It can be up to date or has not
	// yet received the latest block headers from its pears. In case it is synchronizing:
	// - startingBlock: block number this node started to synchronise from
	// - currentBlock:  block number this node is currently importing
	// - highestBlock:  block number of the highest block header this node has received from peers
	// - pulledStates:  number of state entries processed until now
	// - knownStates:   number of known state entries that still need to be pulled
	Syncing(context.Context, *empty.Empty) (*common.SyncingInfo, error)
}

func RegisterChainStateReaderServer(s *grpc.Server, srv ChainStateReaderServer) {
	s.RegisterService(&_ChainStateReader_serviceDesc, srv)
}

func _ChainStateReader_GasPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainStateReaderServer).GasPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cpc.ChainStateReader/GasPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainStateReaderServer).GasPrice(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainStateReader_ProtocolVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainStateReaderServer).ProtocolVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cpc.ChainStateReader/ProtocolVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainStateReaderServer).ProtocolVersion(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainStateReader_Syncing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainStateReaderServer).Syncing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cpc.ChainStateReader/Syncing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainStateReaderServer).Syncing(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChainStateReader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cpc.ChainStateReader",
	HandlerType: (*ChainStateReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GasPrice",
			Handler:    _ChainStateReader_GasPrice_Handler,
		},
		{
			MethodName: "ProtocolVersion",
			Handler:    _ChainStateReader_ProtocolVersion_Handler,
		},
		{
			MethodName: "Syncing",
			Handler:    _ChainStateReader_Syncing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/cpc/cpc.proto",
}

// ChainReaderClient is the client API for ChainReader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChainReaderClient interface {
	// GetBlockCount returns the block number of the chain head.
	GetBlockCount(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*common.BlockNumber, error)
	// GetBalance returns the amount of wei for the given address in the state of the
	// given block number. The rpc.LatestBlockNumber and rpc.PendingBlockNumber meta
	// block numbers are also allowed.
	GetBalance(ctx context.Context, in *ChainReaderRequest, opts ...grpc.CallOption) (*common.Balance, error)
	// GetBlockByNumber returns the requested block. When blockNr is -1 the chain head is returned. When fullTx is true all
	// transactions in the block are returned in full detail, otherwise only the transaction hash is returned.
	GetBlockByNumber(ctx context.Context, in *ChainReaderRequest, opts ...grpc.CallOption) (*common.Block, error)
	// GetBlockByHash returns the requested block. When fullTx is true all transactions in the block are returned in full
	// detail, otherwise only the transaction hash is returned.
	GetBlockByHash(ctx context.Context, in *ChainReaderRequest, opts ...grpc.CallOption) (*common.Block, error)
	// GetCode returns the code stored at the given address in the state for the given block number.
	GetCode(ctx context.Context, in *ChainReaderRequest, opts ...grpc.CallOption) (*common.Code, error)
}

type chainReaderClient struct {
	cc *grpc.ClientConn
}

func NewChainReaderClient(cc *grpc.ClientConn) ChainReaderClient {
	return &chainReaderClient{cc}
}

func (c *chainReaderClient) GetBlockCount(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*common.BlockNumber, error) {
	out := new(common.BlockNumber)
	err := c.cc.Invoke(ctx, "/cpc.ChainReader/GetBlockCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainReaderClient) GetBalance(ctx context.Context, in *ChainReaderRequest, opts ...grpc.CallOption) (*common.Balance, error) {
	out := new(common.Balance)
	err := c.cc.Invoke(ctx, "/cpc.ChainReader/GetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainReaderClient) GetBlockByNumber(ctx context.Context, in *ChainReaderRequest, opts ...grpc.CallOption) (*common.Block, error) {
	out := new(common.Block)
	err := c.cc.Invoke(ctx, "/cpc.ChainReader/GetBlockByNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainReaderClient) GetBlockByHash(ctx context.Context, in *ChainReaderRequest, opts ...grpc.CallOption) (*common.Block, error) {
	out := new(common.Block)
	err := c.cc.Invoke(ctx, "/cpc.ChainReader/GetBlockByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainReaderClient) GetCode(ctx context.Context, in *ChainReaderRequest, opts ...grpc.CallOption) (*common.Code, error) {
	out := new(common.Code)
	err := c.cc.Invoke(ctx, "/cpc.ChainReader/GetCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChainReaderServer is the server API for ChainReader service.
type ChainReaderServer interface {
	// GetBlockCount returns the block number of the chain head.
	GetBlockCount(context.Context, *empty.Empty) (*common.BlockNumber, error)
	// GetBalance returns the amount of wei for the given address in the state of the
	// given block number. The rpc.LatestBlockNumber and rpc.PendingBlockNumber meta
	// block numbers are also allowed.
	GetBalance(context.Context, *ChainReaderRequest) (*common.Balance, error)
	// GetBlockByNumber returns the requested block. When blockNr is -1 the chain head is returned. When fullTx is true all
	// transactions in the block are returned in full detail, otherwise only the transaction hash is returned.
	GetBlockByNumber(context.Context, *ChainReaderRequest) (*common.Block, error)
	// GetBlockByHash returns the requested block. When fullTx is true all transactions in the block are returned in full
	// detail, otherwise only the transaction hash is returned.
	GetBlockByHash(context.Context, *ChainReaderRequest) (*common.Block, error)
	// GetCode returns the code stored at the given address in the state for the given block number.
	GetCode(context.Context, *ChainReaderRequest) (*common.Code, error)
}

func RegisterChainReaderServer(s *grpc.Server, srv ChainReaderServer) {
	s.RegisterService(&_ChainReader_serviceDesc, srv)
}

func _ChainReader_GetBlockCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainReaderServer).GetBlockCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cpc.ChainReader/GetBlockCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainReaderServer).GetBlockCount(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainReader_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainReaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainReaderServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cpc.ChainReader/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainReaderServer).GetBalance(ctx, req.(*ChainReaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainReader_GetBlockByNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainReaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainReaderServer).GetBlockByNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cpc.ChainReader/GetBlockByNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainReaderServer).GetBlockByNumber(ctx, req.(*ChainReaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainReader_GetBlockByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainReaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainReaderServer).GetBlockByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cpc.ChainReader/GetBlockByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainReaderServer).GetBlockByHash(ctx, req.(*ChainReaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainReader_GetCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainReaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainReaderServer).GetCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cpc.ChainReader/GetCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainReaderServer).GetCode(ctx, req.(*ChainReaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChainReader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cpc.ChainReader",
	HandlerType: (*ChainReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlockCount",
			Handler:    _ChainReader_GetBlockCount_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _ChainReader_GetBalance_Handler,
		},
		{
			MethodName: "GetBlockByNumber",
			Handler:    _ChainReader_GetBlockByNumber_Handler,
		},
		{
			MethodName: "GetBlockByHash",
			Handler:    _ChainReader_GetBlockByHash_Handler,
		},
		{
			MethodName: "GetCode",
			Handler:    _ChainReader_GetCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/cpc/cpc.proto",
}

// TransactionPoolReaderClient is the client API for TransactionPoolReader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionPoolReaderClient interface {
	// GetBlockTransactionCountByNumber returns the number of transactions in the block with the given block number.
	GetTransactionCountByBlockNumber(ctx context.Context, in *common.BlockNumber, opts ...grpc.CallOption) (*TransactionCount, error)
	// GetBlockTransactionCountByHash returns the number of transactions in the block with the given hash.
	GetTransactionCountByBlockHash(ctx context.Context, in *common.BlockHash, opts ...grpc.CallOption) (*TransactionCount, error)
	// GetTransactionByBlockNumberAndIndex returns the transaction for the given block number and index.
	GetTransactionByBlockNumberAndIndex(ctx context.Context, in *TransactionPoolReaderRequest, opts ...grpc.CallOption) (*common.RpcTransaction, error)
	// GetTransactionByBlockHashAndIndex returns the transaction for the given block hash and index.
	GetTransactionByBlockHashAndIndex(ctx context.Context, in *TransactionPoolReaderRequest, opts ...grpc.CallOption) (*common.RpcTransaction, error)
	// GetTransactionByHash returns the transaction for the given hash
	GetRawTransactionByBlockNumberAndIndex(ctx context.Context, in *TransactionPoolReaderRequest, opts ...grpc.CallOption) (*RawTransaction, error)
	// GetRawTransactionByBlockHashAndIndex returns the bytes of the transaction for the given block hash and index.
	GetTransactionByHash(ctx context.Context, in *TransactionHash, opts ...grpc.CallOption) (*common.RpcTransaction, error)
	// GetTransactionReceipt returns the transaction receipt for the given transaction hash.
	GetTransactionReceipt(ctx context.Context, in *TransactionHash, opts ...grpc.CallOption) (*common.Receipt, error)
	// GetTransactionCount returns the number of transactions the given address has sent for the given block number
	GetTransactionCount(ctx context.Context, in *TransactionPoolReaderRequest, opts ...grpc.CallOption) (*TransactionCount, error)
}

type transactionPoolReaderClient struct {
	cc *grpc.ClientConn
}

func NewTransactionPoolReaderClient(cc *grpc.ClientConn) TransactionPoolReaderClient {
	return &transactionPoolReaderClient{cc}
}

func (c *transactionPoolReaderClient) GetTransactionCountByBlockNumber(ctx context.Context, in *common.BlockNumber, opts ...grpc.CallOption) (*TransactionCount, error) {
	out := new(TransactionCount)
	err := c.cc.Invoke(ctx, "/cpc.TransactionPoolReader/GetTransactionCountByBlockNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionPoolReaderClient) GetTransactionCountByBlockHash(ctx context.Context, in *common.BlockHash, opts ...grpc.CallOption) (*TransactionCount, error) {
	out := new(TransactionCount)
	err := c.cc.Invoke(ctx, "/cpc.TransactionPoolReader/GetTransactionCountByBlockHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionPoolReaderClient) GetTransactionByBlockNumberAndIndex(ctx context.Context, in *TransactionPoolReaderRequest, opts ...grpc.CallOption) (*common.RpcTransaction, error) {
	out := new(common.RpcTransaction)
	err := c.cc.Invoke(ctx, "/cpc.TransactionPoolReader/GetTransactionByBlockNumberAndIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionPoolReaderClient) GetTransactionByBlockHashAndIndex(ctx context.Context, in *TransactionPoolReaderRequest, opts ...grpc.CallOption) (*common.RpcTransaction, error) {
	out := new(common.RpcTransaction)
	err := c.cc.Invoke(ctx, "/cpc.TransactionPoolReader/GetTransactionByBlockHashAndIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionPoolReaderClient) GetRawTransactionByBlockNumberAndIndex(ctx context.Context, in *TransactionPoolReaderRequest, opts ...grpc.CallOption) (*RawTransaction, error) {
	out := new(RawTransaction)
	err := c.cc.Invoke(ctx, "/cpc.TransactionPoolReader/GetRawTransactionByBlockNumberAndIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionPoolReaderClient) GetTransactionByHash(ctx context.Context, in *TransactionHash, opts ...grpc.CallOption) (*common.RpcTransaction, error) {
	out := new(common.RpcTransaction)
	err := c.cc.Invoke(ctx, "/cpc.TransactionPoolReader/GetTransactionByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionPoolReaderClient) GetTransactionReceipt(ctx context.Context, in *TransactionHash, opts ...grpc.CallOption) (*common.Receipt, error) {
	out := new(common.Receipt)
	err := c.cc.Invoke(ctx, "/cpc.TransactionPoolReader/GetTransactionReceipt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionPoolReaderClient) GetTransactionCount(ctx context.Context, in *TransactionPoolReaderRequest, opts ...grpc.CallOption) (*TransactionCount, error) {
	out := new(TransactionCount)
	err := c.cc.Invoke(ctx, "/cpc.TransactionPoolReader/GetTransactionCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionPoolReaderServer is the server API for TransactionPoolReader service.
type TransactionPoolReaderServer interface {
	// GetBlockTransactionCountByNumber returns the number of transactions in the block with the given block number.
	GetTransactionCountByBlockNumber(context.Context, *common.BlockNumber) (*TransactionCount, error)
	// GetBlockTransactionCountByHash returns the number of transactions in the block with the given hash.
	GetTransactionCountByBlockHash(context.Context, *common.BlockHash) (*TransactionCount, error)
	// GetTransactionByBlockNumberAndIndex returns the transaction for the given block number and index.
	GetTransactionByBlockNumberAndIndex(context.Context, *TransactionPoolReaderRequest) (*common.RpcTransaction, error)
	// GetTransactionByBlockHashAndIndex returns the transaction for the given block hash and index.
	GetTransactionByBlockHashAndIndex(context.Context, *TransactionPoolReaderRequest) (*common.RpcTransaction, error)
	// GetTransactionByHash returns the transaction for the given hash
	GetRawTransactionByBlockNumberAndIndex(context.Context, *TransactionPoolReaderRequest) (*RawTransaction, error)
	// GetRawTransactionByBlockHashAndIndex returns the bytes of the transaction for the given block hash and index.
	GetTransactionByHash(context.Context, *TransactionHash) (*common.RpcTransaction, error)
	// GetTransactionReceipt returns the transaction receipt for the given transaction hash.
	GetTransactionReceipt(context.Context, *TransactionHash) (*common.Receipt, error)
	// GetTransactionCount returns the number of transactions the given address has sent for the given block number
	GetTransactionCount(context.Context, *TransactionPoolReaderRequest) (*TransactionCount, error)
}

func RegisterTransactionPoolReaderServer(s *grpc.Server, srv TransactionPoolReaderServer) {
	s.RegisterService(&_TransactionPoolReader_serviceDesc, srv)
}

func _TransactionPoolReader_GetTransactionCountByBlockNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.BlockNumber)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionPoolReaderServer).GetTransactionCountByBlockNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cpc.TransactionPoolReader/GetTransactionCountByBlockNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionPoolReaderServer).GetTransactionCountByBlockNumber(ctx, req.(*common.BlockNumber))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionPoolReader_GetTransactionCountByBlockHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.BlockHash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionPoolReaderServer).GetTransactionCountByBlockHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cpc.TransactionPoolReader/GetTransactionCountByBlockHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionPoolReaderServer).GetTransactionCountByBlockHash(ctx, req.(*common.BlockHash))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionPoolReader_GetTransactionByBlockNumberAndIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionPoolReaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionPoolReaderServer).GetTransactionByBlockNumberAndIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cpc.TransactionPoolReader/GetTransactionByBlockNumberAndIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionPoolReaderServer).GetTransactionByBlockNumberAndIndex(ctx, req.(*TransactionPoolReaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionPoolReader_GetTransactionByBlockHashAndIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionPoolReaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionPoolReaderServer).GetTransactionByBlockHashAndIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cpc.TransactionPoolReader/GetTransactionByBlockHashAndIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionPoolReaderServer).GetTransactionByBlockHashAndIndex(ctx, req.(*TransactionPoolReaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionPoolReader_GetRawTransactionByBlockNumberAndIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionPoolReaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionPoolReaderServer).GetRawTransactionByBlockNumberAndIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cpc.TransactionPoolReader/GetRawTransactionByBlockNumberAndIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionPoolReaderServer).GetRawTransactionByBlockNumberAndIndex(ctx, req.(*TransactionPoolReaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionPoolReader_GetTransactionByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionHash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionPoolReaderServer).GetTransactionByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cpc.TransactionPoolReader/GetTransactionByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionPoolReaderServer).GetTransactionByHash(ctx, req.(*TransactionHash))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionPoolReader_GetTransactionReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionHash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionPoolReaderServer).GetTransactionReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cpc.TransactionPoolReader/GetTransactionReceipt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionPoolReaderServer).GetTransactionReceipt(ctx, req.(*TransactionHash))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionPoolReader_GetTransactionCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionPoolReaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionPoolReaderServer).GetTransactionCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cpc.TransactionPoolReader/GetTransactionCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionPoolReaderServer).GetTransactionCount(ctx, req.(*TransactionPoolReaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TransactionPoolReader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cpc.TransactionPoolReader",
	HandlerType: (*TransactionPoolReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTransactionCountByBlockNumber",
			Handler:    _TransactionPoolReader_GetTransactionCountByBlockNumber_Handler,
		},
		{
			MethodName: "GetTransactionCountByBlockHash",
			Handler:    _TransactionPoolReader_GetTransactionCountByBlockHash_Handler,
		},
		{
			MethodName: "GetTransactionByBlockNumberAndIndex",
			Handler:    _TransactionPoolReader_GetTransactionByBlockNumberAndIndex_Handler,
		},
		{
			MethodName: "GetTransactionByBlockHashAndIndex",
			Handler:    _TransactionPoolReader_GetTransactionByBlockHashAndIndex_Handler,
		},
		{
			MethodName: "GetRawTransactionByBlockNumberAndIndex",
			Handler:    _TransactionPoolReader_GetRawTransactionByBlockNumberAndIndex_Handler,
		},
		{
			MethodName: "GetTransactionByHash",
			Handler:    _TransactionPoolReader_GetTransactionByHash_Handler,
		},
		{
			MethodName: "GetTransactionReceipt",
			Handler:    _TransactionPoolReader_GetTransactionReceipt_Handler,
		},
		{
			MethodName: "GetTransactionCount",
			Handler:    _TransactionPoolReader_GetTransactionCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/cpc/cpc.proto",
}
